; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=amdgcn-- -mcpu=gfx900 -S -passes=amdgpu-unify-divergent-exit-nodes %s | FileCheck %s

; Verify that AMDGPUUnifyDivergentExitNodes folds a conditional branch whose
; arms originally targeted distinct return blocks (and now both target the
; UnifiedReturnBlock) into an unconditional branch.

declare i32 @llvm.amdgcn.workitem.id.x()

; Both arms of the inner branch target distinct return blocks. After unifying
; the two returns, both arms point at UnifiedReturnBlock and the conditional
; branch must be folded to an unconditional branch. The dead %c1 must be
; cleaned up.
define amdgpu_kernel void @fold_redundant_cond_br(i32 %arg0, i32 %arg1) {
; CHECK-LABEL: define amdgpu_kernel void @fold_redundant_cond_br(
; CHECK-SAME: i32 [[ARG0:%.*]], i32 [[ARG1:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TID:%.*]] = tail call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[C0:%.*]] = icmp slt i32 [[TID]], [[ARG0]]
; CHECK-NEXT:    br i1 [[C0]], label %[[BB1:.*]], label %[[UNIFIEDRETURNBLOCK:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    br label %[[UNIFIEDRETURNBLOCK]]
; CHECK:       [[UNIFIEDRETURNBLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  %tid = tail call i32 @llvm.amdgcn.workitem.id.x()
  %c0 = icmp slt i32 %tid, %arg0
  br i1 %c0, label %inner, label %ret.a

inner:
  %c1 = icmp slt i32 %tid, %arg1
  br i1 %c1, label %ret.a, label %ret.b

ret.a:
  ret void

ret.b:
  ret void
}

; Same shape, but %c1 has an additional non-branch use. The branch is still
; folded, but the icmp must be preserved.
define amdgpu_kernel void @fold_redundant_cond_br_cond_has_other_use(i32 %arg0, i32 %arg1, ptr addrspace(1) %out) {
; CHECK-LABEL: define amdgpu_kernel void @fold_redundant_cond_br_cond_has_other_use(
; CHECK-SAME: i32 [[ARG0:%.*]], i32 [[ARG1:%.*]], ptr addrspace(1) [[OUT:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TID:%.*]] = tail call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[C0:%.*]] = icmp slt i32 [[TID]], [[ARG0]]
; CHECK-NEXT:    br i1 [[C0]], label %[[BB1:.*]], label %[[UNIFIEDRETURNBLOCK:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[C1:%.*]] = icmp slt i32 [[TID]], [[ARG1]]
; CHECK-NEXT:    [[EXT:%.*]] = zext i1 [[C1]] to i32
; CHECK-NEXT:    store i32 [[EXT]], ptr addrspace(1) [[OUT]], align 4
; CHECK-NEXT:    br label %[[UNIFIEDRETURNBLOCK]]
; CHECK:       [[UNIFIEDRETURNBLOCK]]:
; CHECK-NEXT:    ret void
;
entry:
  %tid = tail call i32 @llvm.amdgcn.workitem.id.x()
  %c0 = icmp slt i32 %tid, %arg0
  br i1 %c0, label %inner, label %ret.a

inner:
  %c1 = icmp slt i32 %tid, %arg1
  %ext = zext i1 %c1 to i32
  store i32 %ext, ptr addrspace(1) %out
  br i1 %c1, label %ret.a, label %ret.b

ret.a:
  ret void

ret.b:
  ret void
}
