; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -amdgpu-late-wave-transform=1 -mtriple=amdgpu9.00-amd-amdhsa < %s | FileCheck %s

define i32 @rocrand_regression(ptr addrspace(1) %arg, i32 %arg0, i1 %cmp7) {
; CHECK-LABEL: rocrand_regression:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_and_b32_e32 v0, 1, v3
; CHECK-NEXT:    v_cmp_eq_u32_e32 vcc, 1, v0
; CHECK-NEXT:    v_cndmask_b32_e64 v0, 0, -1, vcc
; CHECK-NEXT:    s_mov_b32 s6, 0
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:  .LBB0_1: ; %while.cond
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    v_cmp_ne_u32_e64 s[8:9], 0, v0
; CHECK-NEXT:    s_xor_b64 s[10:11], exec, s[8:9]
; CHECK-NEXT:    s_or_b64 s[4:5], s[4:5], s[10:11]
; CHECK-NEXT:    s_mov_b64 exec, s[8:9]
; CHECK-NEXT:    ; divergent control-flow edge
; CHECK-NEXT:    s_cbranch_execnz .LBB0_1
; CHECK-NEXT:  .LBB0_2: ; %do.cond
; CHECK-NEXT:    ; in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    s_or_b32 s6, s6, 1
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_cbranch_execnz .LBB0_1
; CHECK-NEXT:  ; %bb.3: ; %DummyReturnBlock
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  br label %do.body

do.body:                                          ; preds = %do.cond, %entry
  %phi.0 = phi i32 [ %arg0, %do.cond ], [ 0, %entry ]
  %phi.1 = phi i32 [ %add6, %do.cond ], [ 0, %entry ]
  %add6 = or i32 %phi.1, 1
  store i32 %phi.1, ptr addrspace(1) %arg, align 4
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %do.body
  %phi.2 = phi i32 [ %phi.0, %do.body ], [ 0, %while.cond ]
  br i1 %cmp7, label %while.cond, label %do.cond

do.cond:                                          ; preds = %while.cond
  br i1 true, label %do.body, label %do.end

do.end:                                           ; preds = %do.cond
  ret i32 %phi.2
}
