; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -amdgpu-late-wave-transform=1 -mtriple=amdgpu9.00 < %s | FileCheck %s

define void @main(i1 %arg) #0 {
; CHECK-LABEL: main:
; CHECK:       ; %bb.0: ; %bb
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; CHECK-NEXT:    buffer_store_dword v8, off, s[0:3], s32 ; 4-byte Folded Spill
; CHECK-NEXT:    buffer_store_dword v9, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    v_writelane_b32 v8, s34, 0
; CHECK-NEXT:    v_writelane_b32 v8, s35, 1
; CHECK-NEXT:    v_writelane_b32 v8, s36, 2
; CHECK-NEXT:    v_writelane_b32 v8, s37, 3
; CHECK-NEXT:    v_writelane_b32 v8, s38, 4
; CHECK-NEXT:    v_writelane_b32 v8, s39, 5
; CHECK-NEXT:    v_writelane_b32 v8, s48, 6
; CHECK-NEXT:    v_writelane_b32 v8, s49, 7
; CHECK-NEXT:    v_writelane_b32 v8, s50, 8
; CHECK-NEXT:    v_writelane_b32 v8, s51, 9
; CHECK-NEXT:    v_writelane_b32 v8, s52, 10
; CHECK-NEXT:    v_writelane_b32 v8, s53, 11
; CHECK-NEXT:    v_writelane_b32 v8, s54, 12
; CHECK-NEXT:    v_writelane_b32 v8, s55, 13
; CHECK-NEXT:    v_writelane_b32 v8, s64, 14
; CHECK-NEXT:    v_writelane_b32 v8, s65, 15
; CHECK-NEXT:    v_writelane_b32 v8, s66, 16
; CHECK-NEXT:    v_writelane_b32 v8, s67, 17
; CHECK-NEXT:    v_writelane_b32 v8, s68, 18
; CHECK-NEXT:    v_writelane_b32 v8, s69, 19
; CHECK-NEXT:    v_writelane_b32 v8, s70, 20
; CHECK-NEXT:    v_writelane_b32 v8, s71, 21
; CHECK-NEXT:    v_writelane_b32 v8, s30, 22
; CHECK-NEXT:    v_writelane_b32 v8, s31, 23
; CHECK-NEXT:    s_getpc_b64 s[4:5]
; CHECK-NEXT:    s_mov_b32 s29, s4
; CHECK-NEXT:    s_mov_b64 s[4:5], 0
; CHECK-NEXT:    s_mov_b32 s28, 0
; CHECK-NEXT:    s_load_dwordx4 s[68:71], s[4:5], 0x0
; CHECK-NEXT:    s_load_dwordx8 s[20:27], s[28:29], 0x30
; CHECK-NEXT:    s_load_dwordx16 s[52:67], s[28:29], 0xf0
; CHECK-NEXT:    ; kill: killed $sgpr4_sgpr5
; CHECK-NEXT:    s_nop 0
; CHECK-NEXT:    s_load_dwordx16 s[4:19], s[28:29], 0x130
; CHECK-NEXT:    s_load_dwordx16 s[36:51], s[28:29], 0x1f0
; CHECK-NEXT:    ; implicit-def: $vgpr9 : SGPR spill to VGPR lane
; CHECK-NEXT:    v_mov_b32_e32 v2, 0
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v1, s68
; CHECK-NEXT:    s_mov_b32 s30, s28
; CHECK-NEXT:    s_mov_b32 s31, s28
; CHECK-NEXT:    v_writelane_b32 v9, s36, 0
; CHECK-NEXT:    v_writelane_b32 v9, s37, 1
; CHECK-NEXT:    v_writelane_b32 v9, s38, 2
; CHECK-NEXT:    v_writelane_b32 v9, s39, 3
; CHECK-NEXT:    v_writelane_b32 v9, s40, 4
; CHECK-NEXT:    v_writelane_b32 v9, s41, 5
; CHECK-NEXT:    v_writelane_b32 v9, s42, 6
; CHECK-NEXT:    v_writelane_b32 v9, s43, 7
; CHECK-NEXT:    v_writelane_b32 v9, s44, 8
; CHECK-NEXT:    v_writelane_b32 v9, s45, 9
; CHECK-NEXT:    v_writelane_b32 v9, s46, 10
; CHECK-NEXT:    v_writelane_b32 v9, s47, 11
; CHECK-NEXT:    v_writelane_b32 v9, s48, 12
; CHECK-NEXT:    v_writelane_b32 v9, s49, 13
; CHECK-NEXT:    v_writelane_b32 v9, s50, 14
; CHECK-NEXT:    v_writelane_b32 v9, s51, 15
; CHECK-NEXT:    v_writelane_b32 v9, s52, 16
; CHECK-NEXT:    v_writelane_b32 v9, s53, 17
; CHECK-NEXT:    v_writelane_b32 v9, s54, 18
; CHECK-NEXT:    v_writelane_b32 v9, s55, 19
; CHECK-NEXT:    v_writelane_b32 v9, s56, 20
; CHECK-NEXT:    v_writelane_b32 v9, s57, 21
; CHECK-NEXT:    v_writelane_b32 v9, s58, 22
; CHECK-NEXT:    v_writelane_b32 v9, s59, 23
; CHECK-NEXT:    v_writelane_b32 v9, s60, 24
; CHECK-NEXT:    v_writelane_b32 v9, s61, 25
; CHECK-NEXT:    v_writelane_b32 v9, s62, 26
; CHECK-NEXT:    v_writelane_b32 v9, s63, 27
; CHECK-NEXT:    v_writelane_b32 v9, s64, 28
; CHECK-NEXT:    v_writelane_b32 v9, s65, 29
; CHECK-NEXT:    v_writelane_b32 v9, s66, 30
; CHECK-NEXT:    s_load_dwordx16 s[36:51], s[28:29], 0x2f0
; CHECK-NEXT:    s_mov_b32 s29, s28
; CHECK-NEXT:    v_writelane_b32 v9, s67, 31
; CHECK-NEXT:    v_mov_b32_e32 v3, v2
; CHECK-NEXT:    image_sample_lz v1, v[1:2], s[60:67], s[28:31] dmask:0x1
; CHECK-NEXT:    v_writelane_b32 v9, s4, 32
; CHECK-NEXT:    v_writelane_b32 v9, s5, 33
; CHECK-NEXT:    v_writelane_b32 v9, s6, 34
; CHECK-NEXT:    v_writelane_b32 v9, s7, 35
; CHECK-NEXT:    v_writelane_b32 v9, s8, 36
; CHECK-NEXT:    v_writelane_b32 v9, s9, 37
; CHECK-NEXT:    image_sample_lz v4, v[2:3], s[4:11], s[28:31] dmask:0x1
; CHECK-NEXT:    v_writelane_b32 v9, s10, 38
; CHECK-NEXT:    v_writelane_b32 v9, s11, 39
; CHECK-NEXT:    v_writelane_b32 v9, s12, 40
; CHECK-NEXT:    v_writelane_b32 v9, s13, 41
; CHECK-NEXT:    v_writelane_b32 v9, s14, 42
; CHECK-NEXT:    v_writelane_b32 v9, s15, 43
; CHECK-NEXT:    v_and_b32_e32 v0, 1, v0
; CHECK-NEXT:    v_writelane_b32 v9, s16, 44
; CHECK-NEXT:    v_cmp_eq_u32_e32 vcc, 1, v0
; CHECK-NEXT:    v_writelane_b32 v9, s17, 45
; CHECK-NEXT:    s_xor_b64 s[34:35], vcc, exec
; CHECK-NEXT:    v_writelane_b32 v9, s18, 46
; CHECK-NEXT:    s_mov_b64 s[68:69], s[34:35]
; CHECK-NEXT:    v_writelane_b32 v9, s19, 47
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mul_f32_e32 v4, v4, v1
; CHECK-NEXT:    s_mov_b64 exec, vcc
; CHECK-NEXT:    ; divergent control-flow edge
; CHECK-NEXT:    s_cbranch_execz .LBB0_6
; CHECK-NEXT:  .LBB0_1: ; %bb32
; CHECK-NEXT:    v_cndmask_b32_e64 v0, 0, -1, vcc
; CHECK-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; CHECK-NEXT:    s_xor_b64 s[72:73], vcc, exec
; CHECK-NEXT:    s_mov_b64 exec, vcc
; CHECK-NEXT:    ; divergent control-flow edge
; CHECK-NEXT:    s_cbranch_execz .LBB0_4
; CHECK-NEXT:  .LBB0_2: ; %bb33.preheader
; CHECK-NEXT:    s_mov_b32 s52, 0
; CHECK-NEXT:    s_mov_b32 vcc_lo, s52
; CHECK-NEXT:    s_mov_b32 vcc_hi, s52
; CHECK-NEXT:    v_readlane_b32 s4, v9, 0
; CHECK-NEXT:    s_mov_b32 s53, s52
; CHECK-NEXT:    s_mov_b32 s54, s52
; CHECK-NEXT:    s_mov_b32 s55, s52
; CHECK-NEXT:    v_mov_b32_e32 v0, vcc_lo
; CHECK-NEXT:    v_mov_b32_e32 v1, vcc_hi
; CHECK-NEXT:    v_readlane_b32 s5, v9, 1
; CHECK-NEXT:    v_readlane_b32 s6, v9, 2
; CHECK-NEXT:    v_readlane_b32 s7, v9, 3
; CHECK-NEXT:    v_readlane_b32 s8, v9, 4
; CHECK-NEXT:    v_readlane_b32 s9, v9, 5
; CHECK-NEXT:    v_readlane_b32 s10, v9, 6
; CHECK-NEXT:    v_readlane_b32 s11, v9, 7
; CHECK-NEXT:    s_nop 4
; CHECK-NEXT:    image_sample_lz v5, v[0:1], s[4:11], s[52:55] dmask:0x1
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    image_sample_lz v0, v[0:1], s[36:43], s[52:55] dmask:0x1
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_and_b64 vcc, exec, -1
; CHECK-NEXT:    v_readlane_b32 s12, v9, 8
; CHECK-NEXT:    v_readlane_b32 s13, v9, 9
; CHECK-NEXT:    v_readlane_b32 s14, v9, 10
; CHECK-NEXT:    v_readlane_b32 s15, v9, 11
; CHECK-NEXT:    v_readlane_b32 s16, v9, 12
; CHECK-NEXT:    v_readlane_b32 s17, v9, 13
; CHECK-NEXT:    v_readlane_b32 s18, v9, 14
; CHECK-NEXT:    v_readlane_b32 s19, v9, 15
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_f32_e32 v0, v0, v5
; CHECK-NEXT:    v_mul_f32_e32 v0, v0, v4
; CHECK-NEXT:  .LBB0_3: ; %bb33
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    v_add_f32_e32 v5, v1, v0
; CHECK-NEXT:    v_sub_f32_e32 v1, v1, v5
; CHECK-NEXT:    s_mov_b64 vcc, vcc
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_3
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    s_or_b64 exec, exec, s[72:73]
; CHECK-NEXT:    s_xor_b64 s[4:5], exec, s[72:73]
; CHECK-NEXT:    s_and_b64 s[4:5], s[4:5], exec
; CHECK-NEXT:    s_or_b64 s[68:69], s[68:69], s[4:5]
; CHECK-NEXT:    s_mov_b64 exec, s[72:73]
; CHECK-NEXT:    ; divergent control-flow edge
; CHECK-NEXT:    s_cbranch_execz .LBB0_6
; CHECK-NEXT:  .LBB0_5: ; %bb43
; CHECK-NEXT:    s_mov_b32 s4, 0
; CHECK-NEXT:    s_mov_b32 s5, s4
; CHECK-NEXT:    v_readlane_b32 s52, v9, 16
; CHECK-NEXT:    v_mov_b32_e32 v0, s4
; CHECK-NEXT:    v_mov_b32_e32 v1, s5
; CHECK-NEXT:    s_mov_b32 s6, s4
; CHECK-NEXT:    s_mov_b32 s7, s4
; CHECK-NEXT:    v_readlane_b32 s53, v9, 17
; CHECK-NEXT:    v_readlane_b32 s54, v9, 18
; CHECK-NEXT:    v_readlane_b32 s55, v9, 19
; CHECK-NEXT:    v_readlane_b32 s56, v9, 20
; CHECK-NEXT:    v_readlane_b32 s57, v9, 21
; CHECK-NEXT:    v_readlane_b32 s58, v9, 22
; CHECK-NEXT:    v_readlane_b32 s59, v9, 23
; CHECK-NEXT:    v_readlane_b32 s60, v9, 24
; CHECK-NEXT:    v_readlane_b32 s61, v9, 25
; CHECK-NEXT:    v_readlane_b32 s62, v9, 26
; CHECK-NEXT:    v_readlane_b32 s63, v9, 27
; CHECK-NEXT:    v_readlane_b32 s64, v9, 28
; CHECK-NEXT:    v_readlane_b32 s65, v9, 29
; CHECK-NEXT:    v_readlane_b32 s66, v9, 30
; CHECK-NEXT:    v_readlane_b32 s67, v9, 31
; CHECK-NEXT:    image_sample_lz v5, v[0:1], s[52:59], s[4:7] dmask:0x1
; CHECK-NEXT:    v_readlane_b32 s52, v9, 32
; CHECK-NEXT:    v_readlane_b32 s60, v9, 40
; CHECK-NEXT:    v_readlane_b32 s61, v9, 41
; CHECK-NEXT:    v_readlane_b32 s62, v9, 42
; CHECK-NEXT:    v_readlane_b32 s63, v9, 43
; CHECK-NEXT:    v_readlane_b32 s64, v9, 44
; CHECK-NEXT:    v_readlane_b32 s65, v9, 45
; CHECK-NEXT:    v_readlane_b32 s66, v9, 46
; CHECK-NEXT:    v_readlane_b32 s67, v9, 47
; CHECK-NEXT:    v_mov_b32_e32 v6, 0
; CHECK-NEXT:    v_mov_b32_e32 v7, v6
; CHECK-NEXT:    v_readlane_b32 s53, v9, 33
; CHECK-NEXT:    v_readlane_b32 s54, v9, 34
; CHECK-NEXT:    v_readlane_b32 s55, v9, 35
; CHECK-NEXT:    image_sample_lz v0, v[0:1], s[60:67], s[20:23] dmask:0x1
; CHECK-NEXT:    v_readlane_b32 s56, v9, 36
; CHECK-NEXT:    v_readlane_b32 s57, v9, 37
; CHECK-NEXT:    v_readlane_b32 s58, v9, 38
; CHECK-NEXT:    v_readlane_b32 s59, v9, 39
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dwordx3 v[5:7], off, s[4:7], 0
; CHECK-NEXT:    s_waitcnt vmcnt(1)
; CHECK-NEXT:    buffer_store_dwordx4 v[0:3], off, s[4:7], 0
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    s_or_b64 exec, exec, s[68:69]
; CHECK-NEXT:    s_xor_b64 s[4:5], exec, s[34:35]
; CHECK-NEXT:    s_mov_b64 exec, s[34:35]
; CHECK-NEXT:    v_readlane_b32 s8, v9, 0
; CHECK-NEXT:    v_readlane_b32 s16, v9, 8
; CHECK-NEXT:    v_readlane_b32 s17, v9, 9
; CHECK-NEXT:    v_readlane_b32 s18, v9, 10
; CHECK-NEXT:    v_readlane_b32 s19, v9, 11
; CHECK-NEXT:    v_readlane_b32 s20, v9, 12
; CHECK-NEXT:    v_readlane_b32 s21, v9, 13
; CHECK-NEXT:    v_readlane_b32 s22, v9, 14
; CHECK-NEXT:    v_readlane_b32 s23, v9, 15
; CHECK-NEXT:    v_readlane_b32 s9, v9, 1
; CHECK-NEXT:    v_readlane_b32 s10, v9, 2
; CHECK-NEXT:    v_readlane_b32 s11, v9, 3
; CHECK-NEXT:    v_readlane_b32 s12, v9, 4
; CHECK-NEXT:    v_readlane_b32 s13, v9, 5
; CHECK-NEXT:    v_readlane_b32 s14, v9, 6
; CHECK-NEXT:    v_readlane_b32 s15, v9, 7
; CHECK-NEXT:    ; divergent control-flow edge
; CHECK-NEXT:    s_cbranch_execz .LBB0_9
; CHECK-NEXT:  .LBB0_7: ; %bb48
; CHECK-NEXT:    v_readlane_b32 s52, v9, 16
; CHECK-NEXT:    v_readlane_b32 s60, v9, 24
; CHECK-NEXT:    v_readlane_b32 s61, v9, 25
; CHECK-NEXT:    v_readlane_b32 s62, v9, 26
; CHECK-NEXT:    v_readlane_b32 s63, v9, 27
; CHECK-NEXT:    v_readlane_b32 s64, v9, 28
; CHECK-NEXT:    v_readlane_b32 s65, v9, 29
; CHECK-NEXT:    v_readlane_b32 s66, v9, 30
; CHECK-NEXT:    v_readlane_b32 s67, v9, 31
; CHECK-NEXT:    s_mov_b64 s[12:13], s[16:17]
; CHECK-NEXT:    s_mov_b64 s[14:15], s[18:19]
; CHECK-NEXT:    s_mov_b64 s[16:17], s[20:21]
; CHECK-NEXT:    s_mov_b64 s[18:19], s[22:23]
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    image_sample_lz v0, v[2:3], s[60:67], s[28:31] dmask:0x1
; CHECK-NEXT:    s_and_b64 vcc, exec, -1
; CHECK-NEXT:    v_readlane_b32 s53, v9, 17
; CHECK-NEXT:    v_readlane_b32 s54, v9, 18
; CHECK-NEXT:    v_readlane_b32 s55, v9, 19
; CHECK-NEXT:    v_readlane_b32 s56, v9, 20
; CHECK-NEXT:    v_readlane_b32 s57, v9, 21
; CHECK-NEXT:    v_readlane_b32 s58, v9, 22
; CHECK-NEXT:    v_readlane_b32 s59, v9, 23
; CHECK-NEXT:  .LBB0_8: ; %bb50
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    image_sample_lz v3, v[1:2], s[12:19], s[24:27] dmask:0x1
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    image_sample_lz v5, v[1:2], s[44:51], s[28:31] dmask:0x1
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_sub_f32_e32 v1, v5, v3
; CHECK-NEXT:    v_mul_f32_e32 v1, v1, v4
; CHECK-NEXT:    v_mul_f32_e32 v1, v1, v0
; CHECK-NEXT:    s_mov_b64 vcc, vcc
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_8
; CHECK-NEXT:  .LBB0_9: ; %UnifiedReturnBlock
; CHECK-NEXT:    s_or_b64 exec, exec, s[4:5]
; CHECK-NEXT:    v_readlane_b32 s30, v8, 22
; CHECK-NEXT:    v_readlane_b32 s31, v8, 23
; CHECK-NEXT:    v_readlane_b32 s71, v8, 21
; CHECK-NEXT:    v_readlane_b32 s70, v8, 20
; CHECK-NEXT:    v_readlane_b32 s69, v8, 19
; CHECK-NEXT:    v_readlane_b32 s68, v8, 18
; CHECK-NEXT:    v_readlane_b32 s67, v8, 17
; CHECK-NEXT:    v_readlane_b32 s66, v8, 16
; CHECK-NEXT:    v_readlane_b32 s65, v8, 15
; CHECK-NEXT:    v_readlane_b32 s64, v8, 14
; CHECK-NEXT:    v_readlane_b32 s55, v8, 13
; CHECK-NEXT:    v_readlane_b32 s54, v8, 12
; CHECK-NEXT:    v_readlane_b32 s53, v8, 11
; CHECK-NEXT:    v_readlane_b32 s52, v8, 10
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    v_readlane_b32 s51, v8, 9
; CHECK-NEXT:    v_readlane_b32 s50, v8, 8
; CHECK-NEXT:    v_readlane_b32 s49, v8, 7
; CHECK-NEXT:    v_readlane_b32 s48, v8, 6
; CHECK-NEXT:    v_readlane_b32 s39, v8, 5
; CHECK-NEXT:    v_readlane_b32 s38, v8, 4
; CHECK-NEXT:    v_readlane_b32 s37, v8, 3
; CHECK-NEXT:    v_readlane_b32 s36, v8, 2
; CHECK-NEXT:    v_readlane_b32 s35, v8, 1
; CHECK-NEXT:    v_readlane_b32 s34, v8, 0
; CHECK-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; CHECK-NEXT:    buffer_load_dword v8, off, s[0:3], s32 ; 4-byte Folded Reload
; CHECK-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; CHECK-NEXT:    s_mov_b64 exec, s[4:5]
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
bb:
  %i = call i64 @llvm.amdgcn.s.getpc()
  %i1 = trunc i64 %i to i32
  %i2 = insertelement <2 x i32> zeroinitializer, i32 %i1, i64 1
  %i3 = bitcast <2 x i32> %i2 to i64
  %i4 = inttoptr i64 %i3 to ptr addrspace(4)
  %i5 = getelementptr i8, ptr addrspace(4) %i4, i64 48
  %i6 = load <4 x i32>, ptr addrspace(4) %i5, align 16
  %i7 = getelementptr i8, ptr addrspace(4) %i4, i64 64
  %i8 = load <4 x i32>, ptr addrspace(4) %i7, align 16
  %i9 = getelementptr i8, ptr addrspace(4) %i4, i64 240
  %i10 = load <8 x i32>, ptr addrspace(4) %i9, align 32
  %i11 = getelementptr i8, ptr addrspace(4) %i4, i64 272
  %i12 = load <8 x i32>, ptr addrspace(4) %i11, align 32
  %i13 = getelementptr i8, ptr addrspace(4) %i4, i64 304
  %i14 = load <8 x i32>, ptr addrspace(4) %i13, align 32
  %i15 = getelementptr i8, ptr addrspace(4) %i4, i64 336
  %i16 = load <8 x i32>, ptr addrspace(4) %i15, align 32
  %i17 = getelementptr i8, ptr addrspace(4) %i4, i64 496
  %i18 = load <8 x i32>, ptr addrspace(4) %i17, align 32
  %i19 = getelementptr i8, ptr addrspace(4) %i4, i64 528
  %i20 = load <8 x i32>, ptr addrspace(4) %i19, align 32
  %i21 = getelementptr i8, ptr addrspace(4) %i4, i64 752
  %i22 = load <8 x i32>, ptr addrspace(4) %i21, align 32
  %i23 = getelementptr i8, ptr addrspace(4) %i4, i64 784
  %i24 = load <8 x i32>, ptr addrspace(4) %i23, align 32
  %i25 = load <4 x float>, ptr addrspace(4) null, align 16
  %i26 = extractelement <4 x float> %i25, i64 0
  %i27 = call float @llvm.amdgcn.image.sample.lz.2d.f32.f32(i32 1, float %i26, float 0.000000e+00, <8 x i32> %i12, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i28 = call <4 x float> @llvm.amdgcn.image.sample.lz.2d.v4f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i14, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i29 = extractelement <4 x float> %i28, i64 0
  %i30 = fmul float %i29, %i27
  %i31 = call <4 x float> @llvm.amdgcn.image.sample.lz.2d.v4f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i16, <4 x i32> %i6, i1 false, i32 0, i32 0)
  br i1 %arg, label %bb32, label %bb48

bb32:                                             ; preds = %bb
  br i1 %arg, label %bb33, label %bb43

bb33:                                             ; preds = %bb33, %bb32
  %i34 = phi float [ %i42, %bb33 ], [ 0.000000e+00, %bb32 ]
  %i35 = call <2 x float> @llvm.amdgcn.image.sample.lz.2d.v2f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i18, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i36 = extractelement <2 x float> %i35, i64 0
  %i37 = call <2 x float> @llvm.amdgcn.image.sample.lz.2d.v2f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i22, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i38 = extractelement <2 x float> %i37, i64 0
  %i39 = fsub float %i38, %i36
  %i40 = fmul float %i39, %i30
  %i41 = fadd float %i34, %i40
  %i42 = fsub float %i34, %i41
  br label %bb33

bb43:                                             ; preds = %bb32
  %i44 = call float @llvm.amdgcn.image.sample.lz.2d.f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i10, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i45 = bitcast float %i44 to i32
  %i46 = insertelement <3 x i32> zeroinitializer, i32 %i45, i64 0
  call void @llvm.amdgcn.raw.buffer.store.v3i32(<3 x i32> %i46, <4 x i32> zeroinitializer, i32 0, i32 0, i32 0)
  %i47 = bitcast <4 x float> %i31 to <4 x i32>
  call void @llvm.amdgcn.raw.buffer.store.v4i32(<4 x i32> %i47, <4 x i32> zeroinitializer, i32 0, i32 0, i32 0)
  ret void

bb48:                                             ; preds = %bb
  %i49 = call float @llvm.amdgcn.image.sample.lz.2d.f32.f32(i32 1, float 0.000000e+00, float 0.000000e+00, <8 x i32> %i12, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  br label %bb50

bb50:                                             ; preds = %bb50, %bb48
  %i51 = phi float [ 0.000000e+00, %bb48 ], [ %i58, %bb50 ]
  %i52 = call <2 x float> @llvm.amdgcn.image.sample.lz.2d.v2f32.f32(i32 1, float %i51, float 0.000000e+00, <8 x i32> %i20, <4 x i32> %i8, i1 false, i32 0, i32 0)
  %i53 = extractelement <2 x float> %i52, i64 0
  %i54 = call <2 x float> @llvm.amdgcn.image.sample.lz.2d.v2f32.f32(i32 1, float %i51, float 0.000000e+00, <8 x i32> %i24, <4 x i32> zeroinitializer, i1 false, i32 0, i32 0)
  %i55 = extractelement <2 x float> %i54, i64 0
  %i56 = fsub float %i55, %i53
  %i57 = fmul float %i56, %i30
  %i58 = fmul float %i57, %i49
  br label %bb50
}

declare i64 @llvm.amdgcn.s.getpc() #1
declare <4 x float> @llvm.amdgcn.image.sample.lz.2d.v4f32.f32(i32 immarg, float, float, <8 x i32>, <4 x i32>, i1 immarg, i32 immarg, i32 immarg) #2
declare float @llvm.amdgcn.image.sample.lz.2d.f32.f32(i32 immarg, float, float, <8 x i32>, <4 x i32>, i1 immarg, i32 immarg, i32 immarg) #2
declare <2 x float> @llvm.amdgcn.image.sample.lz.2d.v2f32.f32(i32 immarg, float, float, <8 x i32>, <4 x i32>, i1 immarg, i32 immarg, i32 immarg) #2
declare void @llvm.amdgcn.raw.buffer.store.v3i32(<3 x i32>, <4 x i32>, i32, i32, i32 immarg) #3
declare void @llvm.amdgcn.raw.buffer.store.v4i32(<4 x i32>, <4 x i32>, i32, i32, i32 immarg) #3

attributes #0 = { nounwind "amdgpu-waves-per-eu"="10,10" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(read) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(write) }
