; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; NOTE: Tests SelectionDAG (default llc) lowering of uniform @llvm.usub.sat
; to scalar SOPs (s_max_u32 + s_sub_i32). GlobalISel coverage lives in
; GlobalISel/usubsat.ll.
;
; RUN: llc -mtriple=amdgcn-amd-amdpal -mcpu=gfx1201 < %s | FileCheck %s

declare i32 @llvm.usub.sat.i32(i32, i32)
declare i16 @llvm.usub.sat.i16(i16, i16)

define amdgpu_ps i32 @uniform_usubsat_i32(i32 inreg %a, i32 inreg %b) {
; CHECK-LABEL: uniform_usubsat_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_max_u32 s0, s0, s1
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_sub_co_i32 s0, s0, s1
; CHECK-NEXT:    ; return to shader part epilog
  %r = call i32 @llvm.usub.sat.i32(i32 %a, i32 %b)
  ret i32 %r
}

define amdgpu_ps i16 @uniform_usubsat_i16(i16 inreg %a, i16 inreg %b) {
; CHECK-LABEL: uniform_usubsat_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_and_b32 s1, s1, 0xffff
; CHECK-NEXT:    s_and_b32 s0, s0, 0xffff
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_max_u32 s0, s0, s1
; CHECK-NEXT:    s_sub_co_i32 s0, s0, s1
; CHECK-NEXT:    ; return to shader part epilog
  %r = call i16 @llvm.usub.sat.i16(i16 %a, i16 %b)
  ret i16 %r
}
