; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=slp-vectorizer -mattr=+avx2 < %s | FileCheck %s

; The mul lane is emitted as shl by 20; the node must not be demoted below
; 32 bits, otherwise the shift amount is out of range and produces poison.
define void @test(ptr %p, ptr %in) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[P:%.*]], ptr [[IN:%.*]]) {
; CHECK-NEXT:    [[L0:%.*]] = load i8, ptr [[IN]], align 1
; CHECK-NEXT:    [[GI1:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 1
; CHECK-NEXT:    [[L1:%.*]] = load i8, ptr [[GI1]], align 1
; CHECK-NEXT:    [[GI2:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 2
; CHECK-NEXT:    [[L2:%.*]] = load i8, ptr [[GI2]], align 1
; CHECK-NEXT:    [[GI3:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 3
; CHECK-NEXT:    [[L3:%.*]] = load i8, ptr [[GI3]], align 1
; CHECK-NEXT:    [[Z0:%.*]] = zext i8 [[L0]] to i32
; CHECK-NEXT:    [[Z1:%.*]] = zext i8 [[L1]] to i32
; CHECK-NEXT:    [[Z2:%.*]] = zext i8 [[L2]] to i32
; CHECK-NEXT:    [[Z3:%.*]] = zext i8 [[L3]] to i32
; CHECK-NEXT:    [[X0:%.*]] = and i32 [[Z0]], 7
; CHECK-NEXT:    [[X1:%.*]] = and i32 [[Z1]], 7
; CHECK-NEXT:    [[X2:%.*]] = and i32 [[Z2]], 7
; CHECK-NEXT:    [[X3:%.*]] = and i32 [[Z3]], 7
; CHECK-NEXT:    [[S0:%.*]] = shl i32 [[X0]], 3
; CHECK-NEXT:    [[S1:%.*]] = mul i32 1048576, [[X1]]
; CHECK-NEXT:    [[S2:%.*]] = shl i32 [[X2]], 3
; CHECK-NEXT:    [[S3:%.*]] = shl i32 [[X3]], 3
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[S0]] to i8
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i32 [[S1]] to i8
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[S2]] to i8
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[S3]] to i8
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[P]], align 1
; CHECK-NEXT:    [[G1:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 1
; CHECK-NEXT:    store i8 [[TMP7]], ptr [[G1]], align 1
; CHECK-NEXT:    [[G2:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 2
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[G2]], align 1
; CHECK-NEXT:    [[G3:%.*]] = getelementptr inbounds i8, ptr [[P]], i64 3
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[G3]], align 1
; CHECK-NEXT:    ret void
;
  %l0 = load i8, ptr %in, align 1
  %gi1 = getelementptr inbounds i8, ptr %in, i64 1
  %l1 = load i8, ptr %gi1, align 1
  %gi2 = getelementptr inbounds i8, ptr %in, i64 2
  %l2 = load i8, ptr %gi2, align 1
  %gi3 = getelementptr inbounds i8, ptr %in, i64 3
  %l3 = load i8, ptr %gi3, align 1
  %z0 = zext i8 %l0 to i32
  %z1 = zext i8 %l1 to i32
  %z2 = zext i8 %l2 to i32
  %z3 = zext i8 %l3 to i32
  %x0 = and i32 %z0, 7
  %x1 = and i32 %z1, 7
  %x2 = and i32 %z2, 7
  %x3 = and i32 %z3, 7
  %s0 = shl i32 %x0, 3
  %s1 = mul i32 1048576, %x1
  %s2 = shl i32 %x2, 3
  %s3 = shl i32 %x3, 3
  %t0 = trunc i32 %s0 to i8
  %t1 = trunc i32 %s1 to i8
  %t2 = trunc i32 %s2 to i8
  %t3 = trunc i32 %s3 to i8
  store i8 %t0, ptr %p, align 1
  %g1 = getelementptr inbounds i8, ptr %p, i64 1
  store i8 %t1, ptr %g1, align 1
  %g2 = getelementptr inbounds i8, ptr %p, i64 2
  store i8 %t2, ptr %g2, align 1
  %g3 = getelementptr inbounds i8, ptr %p, i64 3
  store i8 %t3, ptr %g3, align 1
  ret void
}
