// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: amdgpu-registered-target
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -mcode-object-version=5 -target-cpu tahiti -emit-llvm -o - %s | FileCheck -check-prefixes=NONUNIFORM-V5  %s
// RUN: %clang_cc1 -cl-std=CL2.0 -cl-uniform-work-group-size -triple amdgcn-unknown-unknown -mcode-object-version=5 -target-cpu tahiti -emit-llvm -o - %s | FileCheck -check-prefixes=UNIFORM-V5  %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -mcode-object-version=4 -target-cpu tahiti -emit-llvm -o - %s | FileCheck -check-prefixes=NONUNIFORM-V4  %s
// RUN: %clang_cc1 -cl-std=CL2.0 -cl-uniform-work-group-size -triple amdgcn-unknown-unknown -mcode-object-version=4 -target-cpu tahiti -emit-llvm -o - %s | FileCheck -check-prefixes=UNIFORM-V4  %s
// RUN: %clang_cc1 -cl-std=CL2.0 -triple amdgcn-unknown-unknown -mcode-object-version=none -emit-llvm -o - %s | FileCheck -check-prefixes=NONUNIFORM-UNKNOWN  %s
// RUN: %clang_cc1 -cl-std=CL2.0 -cl-uniform-work-group-size -triple amdgcn-unknown-unknown -mcode-object-version=none -emit-llvm -o - %s | FileCheck -check-prefixes=UNIFORM-UNKNOWN  %s


// NONUNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// NONUNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NONUNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 12
// NONUNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7:![0-9]+]], !invariant.load [[META8:![0-9]+]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// UNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// UNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 12
// UNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7:![0-9]+]], !invariant.load [[META8:![0-9]+]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// NONUNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NONUNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 4
// NONUNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7:![0-9]+]], !invariant.load [[META8:![0-9]+]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// UNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// UNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 4
// UNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7:![0-9]+]], !invariant.load [[META8:![0-9]+]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// NONUNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// NONUNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 12
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6:![0-9]+]], !invariant.load [[META7:![0-9]+]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// NONUNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_x(
// UNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// UNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 12
// UNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6:![0-9]+]], !invariant.load [[META7:![0-9]+]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// UNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
unsigned int test_get_workgroup_size_x()
{
    return __builtin_amdgcn_workgroup_size_x();
}

// NONUNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// NONUNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 14
// NONUNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// UNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 14
// UNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// NONUNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 6
// NONUNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// UNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 6
// UNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// NONUNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 14
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 6
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 2, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// NONUNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_y(
// UNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 14
// UNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 6
// UNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 2, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// UNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
unsigned int test_get_workgroup_size_y()
{
    return __builtin_amdgcn_workgroup_size_y();
}

// NONUNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// NONUNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 16
// NONUNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 8, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V5-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// UNIFORM-V5-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-V5-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 16
// UNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 8, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V5-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// NONUNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 8
// NONUNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// NONUNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-V4-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// UNIFORM-V4-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-V4-NEXT:  [[ENTRY:.*:]]
// UNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 8
// UNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP2]] to i32
// UNIFORM-V4-NEXT:    ret i32 [[CONV]]
//
// NONUNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// NONUNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0]] {
// NONUNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 16
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 8
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// NONUNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
// UNIFORM-UNKNOWN-LABEL: define dso_local range(i32 1, 1025) i32 @test_get_workgroup_size_z(
// UNIFORM-UNKNOWN-SAME: ) local_unnamed_addr #[[ATTR0]] {
// UNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*:]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 16
// UNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 8
// UNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    [[CONV:%.*]] = zext nneg i16 [[TMP7]] to i32
// UNIFORM-UNKNOWN-NEXT:    ret i32 [[CONV]]
//
unsigned int test_get_workgroup_size_z()
{
    return __builtin_amdgcn_workgroup_size_z();
}

// NONUNIFORM-V5-LABEL: define dso_local void @test_get_workgroup_size(
// NONUNIFORM-V5-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// NONUNIFORM-V5-NEXT:  [[ENTRY:.*]]:
// NONUNIFORM-V5-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// NONUNIFORM-V5-NEXT:      i32 0, label %[[SW_BB:.*]]
// NONUNIFORM-V5-NEXT:      i32 1, label %[[SW_BB1:.*]]
// NONUNIFORM-V5-NEXT:      i32 2, label %[[SW_BB3:.*]]
// NONUNIFORM-V5-NEXT:    ]
// NONUNIFORM-V5:       [[SW_BB]]:
// NONUNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 12
// NONUNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP2]], 1
// NONUNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V5:       [[SW_BB1]]:
// NONUNIFORM-V5-NEXT:    [[TMP3:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP3]], i64 14
// NONUNIFORM-V5-NEXT:    [[TMP5:%.*]] = load i16, ptr addrspace(4) [[TMP4]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V5:       [[SW_BB3]]:
// NONUNIFORM-V5-NEXT:    [[TMP6:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-V5-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP6]], i64 16
// NONUNIFORM-V5-NEXT:    [[TMP8:%.*]] = load i16, ptr addrspace(4) [[TMP7]], align 8, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V5:       [[SW_EPILOG]]:
// NONUNIFORM-V5-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP8]], %[[SW_BB3]] ], [ [[TMP5]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// NONUNIFORM-V5-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// NONUNIFORM-V5-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA3:![0-9]+]]
// NONUNIFORM-V5-NEXT:    ret void
//
// UNIFORM-V5-LABEL: define dso_local void @test_get_workgroup_size(
// UNIFORM-V5-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// UNIFORM-V5-NEXT:  [[ENTRY:.*]]:
// UNIFORM-V5-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// UNIFORM-V5-NEXT:      i32 0, label %[[SW_BB:.*]]
// UNIFORM-V5-NEXT:      i32 1, label %[[SW_BB1:.*]]
// UNIFORM-V5-NEXT:      i32 2, label %[[SW_BB3:.*]]
// UNIFORM-V5-NEXT:    ]
// UNIFORM-V5:       [[SW_BB]]:
// UNIFORM-V5-NEXT:    [[TMP0:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 12
// UNIFORM-V5-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP2]], 1
// UNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V5:       [[SW_BB1]]:
// UNIFORM-V5-NEXT:    [[TMP3:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP3]], i64 14
// UNIFORM-V5-NEXT:    [[TMP5:%.*]] = load i16, ptr addrspace(4) [[TMP4]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V5:       [[SW_BB3]]:
// UNIFORM-V5-NEXT:    [[TMP6:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-V5-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP6]], i64 16
// UNIFORM-V5-NEXT:    [[TMP8:%.*]] = load i16, ptr addrspace(4) [[TMP7]], align 8, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V5-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V5:       [[SW_EPILOG]]:
// UNIFORM-V5-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP8]], %[[SW_BB3]] ], [ [[TMP5]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// UNIFORM-V5-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// UNIFORM-V5-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA3:![0-9]+]]
// UNIFORM-V5-NEXT:    ret void
//
// NONUNIFORM-V4-LABEL: define dso_local void @test_get_workgroup_size(
// NONUNIFORM-V4-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// NONUNIFORM-V4-NEXT:  [[ENTRY:.*]]:
// NONUNIFORM-V4-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// NONUNIFORM-V4-NEXT:      i32 0, label %[[SW_BB:.*]]
// NONUNIFORM-V4-NEXT:      i32 1, label %[[SW_BB1:.*]]
// NONUNIFORM-V4-NEXT:      i32 2, label %[[SW_BB3:.*]]
// NONUNIFORM-V4-NEXT:    ]
// NONUNIFORM-V4:       [[SW_BB]]:
// NONUNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 4
// NONUNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP2]], 1
// NONUNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V4:       [[SW_BB1]]:
// NONUNIFORM-V4-NEXT:    [[TMP3:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP3]], i64 6
// NONUNIFORM-V4-NEXT:    [[TMP5:%.*]] = load i16, ptr addrspace(4) [[TMP4]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V4:       [[SW_BB3]]:
// NONUNIFORM-V4-NEXT:    [[TMP6:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-V4-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP6]], i64 8
// NONUNIFORM-V4-NEXT:    [[TMP8:%.*]] = load i16, ptr addrspace(4) [[TMP7]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// NONUNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-V4:       [[SW_EPILOG]]:
// NONUNIFORM-V4-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP8]], %[[SW_BB3]] ], [ [[TMP5]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// NONUNIFORM-V4-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// NONUNIFORM-V4-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA3:![0-9]+]]
// NONUNIFORM-V4-NEXT:    ret void
//
// UNIFORM-V4-LABEL: define dso_local void @test_get_workgroup_size(
// UNIFORM-V4-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// UNIFORM-V4-NEXT:  [[ENTRY:.*]]:
// UNIFORM-V4-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// UNIFORM-V4-NEXT:      i32 0, label %[[SW_BB:.*]]
// UNIFORM-V4-NEXT:      i32 1, label %[[SW_BB1:.*]]
// UNIFORM-V4-NEXT:      i32 2, label %[[SW_BB3:.*]]
// UNIFORM-V4-NEXT:    ]
// UNIFORM-V4:       [[SW_BB]]:
// UNIFORM-V4-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP0]], i64 4
// UNIFORM-V4-NEXT:    [[TMP2:%.*]] = load i16, ptr addrspace(4) [[TMP1]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP2]], 1
// UNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V4:       [[SW_BB1]]:
// UNIFORM-V4-NEXT:    [[TMP3:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP3]], i64 6
// UNIFORM-V4-NEXT:    [[TMP5:%.*]] = load i16, ptr addrspace(4) [[TMP4]], align 2, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V4:       [[SW_BB3]]:
// UNIFORM-V4-NEXT:    [[TMP6:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-V4-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP6]], i64 8
// UNIFORM-V4-NEXT:    [[TMP8:%.*]] = load i16, ptr addrspace(4) [[TMP7]], align 4, !range [[RNG7]], !invariant.load [[META8]], !noundef [[META8]]
// UNIFORM-V4-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-V4:       [[SW_EPILOG]]:
// UNIFORM-V4-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP8]], %[[SW_BB3]] ], [ [[TMP5]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// UNIFORM-V4-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// UNIFORM-V4-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA3:![0-9]+]]
// UNIFORM-V4-NEXT:    ret void
//
// NONUNIFORM-UNKNOWN-LABEL: define dso_local void @test_get_workgroup_size(
// NONUNIFORM-UNKNOWN-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// NONUNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*]]:
// NONUNIFORM-UNKNOWN-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// NONUNIFORM-UNKNOWN-NEXT:      i32 0, label %[[SW_BB:.*]]
// NONUNIFORM-UNKNOWN-NEXT:      i32 1, label %[[SW_BB1:.*]]
// NONUNIFORM-UNKNOWN-NEXT:      i32 2, label %[[SW_BB3:.*]]
// NONUNIFORM-UNKNOWN-NEXT:    ]
// NONUNIFORM-UNKNOWN:       [[SW_BB]]:
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 12
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP7]], 1
// NONUNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-UNKNOWN:       [[SW_BB1]]:
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP9:%.*]] = icmp sgt i32 [[TMP8]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP10:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP10]], i64 14
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP12:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP12]], i64 6
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP14:%.*]] = select i1 [[TMP9]], ptr addrspace(4) [[TMP11]], ptr addrspace(4) [[TMP13]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP15:%.*]] = load i16, ptr addrspace(4) [[TMP14]], align 2, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-UNKNOWN:       [[SW_BB3]]:
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP16:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP17:%.*]] = icmp sgt i32 [[TMP16]], 499
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP18:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP18]], i64 16
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP20:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP20]], i64 8
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP22:%.*]] = select i1 [[TMP17]], ptr addrspace(4) [[TMP19]], ptr addrspace(4) [[TMP21]]
// NONUNIFORM-UNKNOWN-NEXT:    [[TMP23:%.*]] = load i16, ptr addrspace(4) [[TMP22]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// NONUNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// NONUNIFORM-UNKNOWN:       [[SW_EPILOG]]:
// NONUNIFORM-UNKNOWN-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP23]], %[[SW_BB3]] ], [ [[TMP15]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// NONUNIFORM-UNKNOWN-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// NONUNIFORM-UNKNOWN-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA2:![0-9]+]]
// NONUNIFORM-UNKNOWN-NEXT:    ret void
//
// UNIFORM-UNKNOWN-LABEL: define dso_local void @test_get_workgroup_size(
// UNIFORM-UNKNOWN-SAME: i32 noundef [[D:%.*]], ptr addrspace(1) noundef writeonly captures(none) initializes((0, 4)) [[OUT:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// UNIFORM-UNKNOWN-NEXT:  [[ENTRY:.*]]:
// UNIFORM-UNKNOWN-NEXT:    switch i32 [[D]], label %[[SW_EPILOG:.*]] [
// UNIFORM-UNKNOWN-NEXT:      i32 0, label %[[SW_BB:.*]]
// UNIFORM-UNKNOWN-NEXT:      i32 1, label %[[SW_BB1:.*]]
// UNIFORM-UNKNOWN-NEXT:      i32 2, label %[[SW_BB3:.*]]
// UNIFORM-UNKNOWN-NEXT:    ]
// UNIFORM-UNKNOWN:       [[SW_BB]]:
// UNIFORM-UNKNOWN-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[TMP0]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP2:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP2]], i64 12
// UNIFORM-UNKNOWN-NEXT:    [[TMP4:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP4]], i64 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP6:%.*]] = select i1 [[TMP1]], ptr addrspace(4) [[TMP3]], ptr addrspace(4) [[TMP5]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP7:%.*]] = load i16, ptr addrspace(4) [[TMP6]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    [[NARROW:%.*]] = add nuw nsw i16 [[TMP7]], 1
// UNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-UNKNOWN:       [[SW_BB1]]:
// UNIFORM-UNKNOWN-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP9:%.*]] = icmp sgt i32 [[TMP8]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP10:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP10]], i64 14
// UNIFORM-UNKNOWN-NEXT:    [[TMP12:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP12]], i64 6
// UNIFORM-UNKNOWN-NEXT:    [[TMP14:%.*]] = select i1 [[TMP9]], ptr addrspace(4) [[TMP11]], ptr addrspace(4) [[TMP13]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP15:%.*]] = load i16, ptr addrspace(4) [[TMP14]], align 2, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-UNKNOWN:       [[SW_BB3]]:
// UNIFORM-UNKNOWN-NEXT:    [[TMP16:%.*]] = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4
// UNIFORM-UNKNOWN-NEXT:    [[TMP17:%.*]] = icmp sgt i32 [[TMP16]], 499
// UNIFORM-UNKNOWN-NEXT:    [[TMP18:%.*]] = tail call align 8 dereferenceable(256) ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP18]], i64 16
// UNIFORM-UNKNOWN-NEXT:    [[TMP20:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
// UNIFORM-UNKNOWN-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP20]], i64 8
// UNIFORM-UNKNOWN-NEXT:    [[TMP22:%.*]] = select i1 [[TMP17]], ptr addrspace(4) [[TMP19]], ptr addrspace(4) [[TMP21]]
// UNIFORM-UNKNOWN-NEXT:    [[TMP23:%.*]] = load i16, ptr addrspace(4) [[TMP22]], align 4, !range [[RNG6]], !invariant.load [[META7]], !noundef [[META7]]
// UNIFORM-UNKNOWN-NEXT:    br label %[[SW_EPILOG]]
// UNIFORM-UNKNOWN:       [[SW_EPILOG]]:
// UNIFORM-UNKNOWN-NEXT:    [[DOTSINK_SHRUNK:%.*]] = phi i16 [ [[NARROW]], %[[SW_BB]] ], [ [[TMP23]], %[[SW_BB3]] ], [ [[TMP15]], %[[SW_BB1]] ], [ 0, %[[ENTRY]] ]
// UNIFORM-UNKNOWN-NEXT:    [[DOTSINK:%.*]] = zext i16 [[DOTSINK_SHRUNK]] to i32
// UNIFORM-UNKNOWN-NEXT:    store i32 [[DOTSINK]], ptr addrspace(1) [[OUT]], align 4, !tbaa [[INT_TBAA2:![0-9]+]]
// UNIFORM-UNKNOWN-NEXT:    ret void
//
void test_get_workgroup_size(int d, global int *out)
{
	switch (d) {
	case 0: *out = __builtin_amdgcn_workgroup_size_x() + 1; break;
	case 1: *out = __builtin_amdgcn_workgroup_size_y(); break;
	case 2: *out = __builtin_amdgcn_workgroup_size_z(); break;
	default: *out = 0;
	}
}


//.
// NONUNIFORM-V5: [[INT_TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// NONUNIFORM-V5: [[META4]] = !{!"int", [[META5:![0-9]+]], i64 0}
// NONUNIFORM-V5: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// NONUNIFORM-V5: [[META6]] = !{!"Simple C/C++ TBAA"}
// NONUNIFORM-V5: [[RNG7]] = !{i16 1, i16 1025}
// NONUNIFORM-V5: [[META8]] = !{}
//.
// UNIFORM-V5: [[INT_TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// UNIFORM-V5: [[META4]] = !{!"int", [[META5:![0-9]+]], i64 0}
// UNIFORM-V5: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// UNIFORM-V5: [[META6]] = !{!"Simple C/C++ TBAA"}
// UNIFORM-V5: [[RNG7]] = !{i16 1, i16 1025}
// UNIFORM-V5: [[META8]] = !{}
//.
// NONUNIFORM-V4: [[INT_TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// NONUNIFORM-V4: [[META4]] = !{!"int", [[META5:![0-9]+]], i64 0}
// NONUNIFORM-V4: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// NONUNIFORM-V4: [[META6]] = !{!"Simple C/C++ TBAA"}
// NONUNIFORM-V4: [[RNG7]] = !{i16 1, i16 1025}
// NONUNIFORM-V4: [[META8]] = !{}
//.
// UNIFORM-V4: [[INT_TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// UNIFORM-V4: [[META4]] = !{!"int", [[META5:![0-9]+]], i64 0}
// UNIFORM-V4: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// UNIFORM-V4: [[META6]] = !{!"Simple C/C++ TBAA"}
// UNIFORM-V4: [[RNG7]] = !{i16 1, i16 1025}
// UNIFORM-V4: [[META8]] = !{}
//.
// NONUNIFORM-UNKNOWN: [[INT_TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// NONUNIFORM-UNKNOWN: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// NONUNIFORM-UNKNOWN: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// NONUNIFORM-UNKNOWN: [[META5]] = !{!"Simple C/C++ TBAA"}
// NONUNIFORM-UNKNOWN: [[RNG6]] = !{i16 1, i16 1025}
// NONUNIFORM-UNKNOWN: [[META7]] = !{}
//.
// UNIFORM-UNKNOWN: [[INT_TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// UNIFORM-UNKNOWN: [[META3]] = !{!"int", [[META4:![0-9]+]], i64 0}
// UNIFORM-UNKNOWN: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// UNIFORM-UNKNOWN: [[META5]] = !{!"Simple C/C++ TBAA"}
// UNIFORM-UNKNOWN: [[RNG6]] = !{i16 1, i16 1025}
// UNIFORM-UNKNOWN: [[META7]] = !{}
//.
