; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=openmp-opt -S < %s | FileCheck %s

; registerAAsForFunction() seeds AAHeapToStack only when it has seen a call that
; is a candidate for it, and that detection sits in the CallBase block a
; downstream #if 0 covers. With the seeding gone the malloc below survives the
; pass. The %p.h2s alloca is what says the seeding happened.

target triple = "amdgcn-amd-amdhsa"

declare noalias ptr @malloc(i64) allockind("alloc,uninitialized") allocsize(0)

declare void @free(ptr allocptr nocapture) allockind("free")

define i32 @heap_to_stack(i32 %x) {
; CHECK-LABEL: define i32 @heap_to_stack(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[P_H2S:%.*]] = alloca i8, i64 4, align 1, addrspace(5)
; CHECK-NEXT:    [[MALLOC_CAST:%.*]] = addrspacecast ptr addrspace(5) [[P_H2S]] to ptr
; CHECK-NEXT:    store i32 [[X]], ptr [[MALLOC_CAST]], align 4
; CHECK-NEXT:    ret i32 [[X]]
;
  %p = call ptr @malloc(i64 4)
  store i32 %x, ptr %p
  %v = load i32, ptr %p
  call void @free(ptr %p)
  ret i32 %v
}

!llvm.module.flags = !{!0, !1}

!0 = !{i32 7, !"openmp", i32 50}
!1 = !{i32 7, !"openmp-device", i32 50}
