# Keep transitive archives inside the linker rescan group. Preserve the roots
# as well, since mixed linkage can include shared libraries or linker flags.
function(comgr_collect_static_libraries output)
  set(libraries ${ARGN})
  set(pending ${ARGN})
  set(seen)
  while(pending)
    list(GET pending 0 target)
    list(REMOVE_AT pending 0)
    # CMake exports private dependencies of static libraries with LINK_ONLY.
    if(target MATCHES [[^\$<LINK_ONLY:([^<>]+)>$]])
      set(target "${CMAKE_MATCH_1}")
    endif()
    if(NOT TARGET "${target}" OR target IN_LIST seen)
      continue()
    endif()
    list(APPEND seen "${target}")
    get_target_property(type "${target}" TYPE)
    if(type STREQUAL "STATIC_LIBRARY")
      list(APPEND libraries "${target}")
    endif()
    get_target_property(dependencies "${target}" INTERFACE_LINK_LIBRARIES)
    if(dependencies)
      list(APPEND pending ${dependencies})
    endif()
  endwhile()
  list(REMOVE_DUPLICATES libraries)
  set(${output} ${libraries} PARENT_SCOPE)
endfunction()
