# Keep transitive archives inside the linker rescan group. Preserve the roots
# as well, since mixed linkage can include shared libraries or linker flags.
function(comgr_collect_static_libraries output)
  set(libraries ${ARGN})
  set(pending ${ARGN})
  set(seen)
  while(pending)
    list(GET pending 0 target)
    list(REMOVE_AT pending 0)
    # CMake exports private dependencies of static libraries with LINK_ONLY.
    if(target MATCHES [[^\$<LINK_ONLY:([^<>]+)>$]])
      set(target "${CMAKE_MATCH_1}")
    endif()
    if(NOT TARGET "${target}" OR target IN_LIST seen)
      continue()
    endif()
    list(APPEND seen "${target}")
    get_target_property(type "${target}" TYPE)
    if(type STREQUAL "STATIC_LIBRARY")
      list(APPEND libraries "${target}")
    endif()
    get_target_property(dependencies "${target}" INTERFACE_LINK_LIBRARIES)
    if(dependencies)
      list(APPEND pending ${dependencies})
    endif()
  endwhile()
  list(REMOVE_DUPLICATES libraries)
  set(${output} ${libraries} PARENT_SCOPE)
endfunction()

# LLVMConfig exports LLVM_AVAILABLE_LIBS; in-tree LLVM builds instead maintain
# the global LLVM_LIBS property. Both lists can contain shared libraries.
function(comgr_static_llvm_libraries output)
  set(available ${LLVM_AVAILABLE_LIBS})
  if(NOT available)
    get_property(available GLOBAL PROPERTY LLVM_LIBS)
  endif()
  set(libraries)
  foreach(library IN LISTS available)
    get_target_property(type "${library}" TYPE)
    if(type STREQUAL "STATIC_LIBRARY")
      list(APPEND libraries "${library}")
    endif()
  endforeach()
  if(NOT libraries)
    message(FATAL_ERROR "Comgr requires LLVM static component libraries")
  endif()
  set(${output} ${libraries} PARENT_SCOPE)
endfunction()

# Flatten static-library interfaces for this consumer only. File generator
# expressions keep archive locations valid across build configurations.
function(comgr_static_link_libraries consumer)
  set(pending ${ARGN})
  set(seen)
  set(libraries)
  while(pending)
    list(GET pending 0 dependency)
    list(REMOVE_AT pending 0)
    if(dependency MATCHES [[^\$<LINK_ONLY:([^<>]+)>$]])
      set(dependency "${CMAKE_MATCH_1}")
    endif()
    if(TARGET "${dependency}")
      get_target_property(aliased "${dependency}" ALIASED_TARGET)
      if(aliased)
        set(dependency "${aliased}")
      endif()
    endif()
    if(dependency STREQUAL "LLVM" OR dependency IN_LIST seen)
      continue()
    endif()
    list(APPEND seen "${dependency}")
    if(NOT TARGET "${dependency}")
      if(dependency MATCHES [[\$<]])
        message(FATAL_ERROR
          "Unsupported static Comgr link dependency: ${dependency}")
      endif()
      list(APPEND libraries "${dependency}")
      continue()
    endif()
    get_target_property(type "${dependency}" TYPE)
    if(NOT type STREQUAL "STATIC_LIBRARY" AND
       NOT type STREQUAL "INTERFACE_LIBRARY")
      list(APPEND libraries "${dependency}")
      continue()
    endif()
    if(type STREQUAL "STATIC_LIBRARY")
      list(APPEND libraries "$<TARGET_LINKER_FILE:${dependency}>")
      add_dependencies(${consumer} "${dependency}")
    endif()
    # Copy direct usage requirements while visiting each archive's interface;
    # linking the original target would also reintroduce its LLVM dylib edge.
    get_target_property(system_includes "${dependency}"
      INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)
    if(system_includes)
      target_include_directories(${consumer} SYSTEM PRIVATE ${system_includes})
    endif()
    foreach(property IN ITEMS INCLUDE_DIRECTORIES
        COMPILE_DEFINITIONS COMPILE_OPTIONS COMPILE_FEATURES LINK_OPTIONS
        LINK_DIRECTORIES)
      get_target_property(value "${dependency}" "INTERFACE_${property}")
      if(value)
        set_property(TARGET ${consumer} APPEND PROPERTY "${property}" ${value})
      endif()
    endforeach()
    get_target_property(dependencies "${dependency}" INTERFACE_LINK_LIBRARIES)
    if(dependencies)
      list(APPEND pending ${dependencies})
    endif()
  endwhile()
  if(UNIX AND NOT APPLE)
    target_link_libraries(${consumer} PRIVATE
      "-Wl,--start-group" ${libraries} "-Wl,--end-group")
  else()
    target_link_libraries(${consumer} PRIVATE ${libraries})
  endif()
endfunction()
