; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=attributor --attributor-assume-closed-world -S < %s | FileCheck %s

; Specializing an indirect call for a callee that can reach the function holding
; the call site turns an edge that only existed through a function pointer into a
; direct call, closing a call graph cycle. @dispatch would become recursive, and
; a recursive alwaysinline runtime dispatcher cannot be inlined and has no
; statically known stack size on targets without a dynamic stack. @inner is
; specialized, @outer stays on the indirect call.

@g = external global i32

define internal void @dispatch(ptr %fn) {
; CHECK-LABEL: define internal void @dispatch(
; CHECK-SAME: ptr nofree noundef nonnull captures(none) [[FN:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store volatile i32 1, ptr @g, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[FN]], @inner
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB3:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    call void @inner()
; CHECK-NEXT:    br label %[[BB4:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    call void [[FN]](), !callees [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[BB4]]
; CHECK:       [[BB4]]:
; CHECK-NEXT:    ret void
;
  store volatile i32 1, ptr @g
  call void %fn()
  ret void
}

define internal void @outer() {
; CHECK-LABEL: define internal void @outer(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:    store volatile i32 2, ptr @g, align 4
; CHECK-NEXT:    call void @dispatch(ptr nofree noundef nonnull captures(none) @inner) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
  store volatile i32 2, ptr @g
  call void @dispatch(ptr @inner)
  ret void
}

define internal void @inner() {
; CHECK-LABEL: define internal void @inner(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    store volatile i32 3, ptr @g, align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 3, ptr @g
  ret void
}

define void @kernel() {
; CHECK-LABEL: define void @kernel(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:    call void @dispatch(ptr nofree noundef nonnull captures(none) @outer) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
  call void @dispatch(ptr @outer)
  ret void
}
;.
; CHECK: [[META0]] = !{ptr @outer}
;.
