; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes
; RUN: opt < %s -passes=mssaargpromotion -S | FileCheck %s

; REF-LABEL: define internal void @no_ret_blocks() #0 {
; REF-NEXT: unreachable
define internal void @no_ret_blocks() #0 {
; CHECK-LABEL: define {{[^@]+}}@no_ret_blocks
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    unreachable
;
  unreachable
}

define void @no_ret_blocks_caller() {
; CHECK-LABEL: define {{[^@]+}}@no_ret_blocks_caller() {
; CHECK-NEXT:    call void @no_ret_blocks()
; CHECK-NEXT:    ret void
;
  call void @no_ret_blocks()
  ret void
}

; REF-LABEL: @void_one_out_arg_i32_no_use(
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_no_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_no_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @void_one_out_arg_i32_no_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_no_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @void_one_out_arg_i32_no_use()
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_no_use(ptr %val)
  ret void
}

; REF-LABEL: define internal void @skip_byval_arg(
; REF-NEXT: store i32 0, ptr %val
; REF-NEXT: ret void
define internal void @skip_byval_arg(i32* byval(i32) %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_byval_arg
; CHECK-SAME: (ptr byval(i32) [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store i32 0, ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  store i32 0, ptr %val
  ret void
}

define void @skip_byval_arg_caller(i32* byval(i32) %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_byval_arg_caller
; CHECK-SAME: (ptr byval(i32) [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_byval_arg(ptr byval(i32) [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_byval_arg(i32* byval(i32) %val)
  ret void
}

; REF-LABEL: define internal void @skip_optnone(
; REF-NEXT: store i32 0, ptr %val
; REF-NEXT: ret void
define internal void @skip_optnone(ptr %val) #1 {
; CHECK-LABEL: define {{[^@]+}}@skip_optnone
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    store i32 0, ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  store i32 0, ptr %val
  ret void
}

define void @skip_optnone_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_optnone_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_optnone(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_optnone(ptr %val)
  ret void
}

; REF-LABEL: define internal void @skip_volatile(
; REF-NEXT: store volatile i32 0, ptr %val
; REF-NEXT: ret void
define internal void @skip_volatile(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_volatile
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store volatile i32 0, ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  store volatile i32 0, ptr %val
  ret void
}

define void @skip_volatile_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_volatile_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_volatile(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_volatile(ptr %val)
  ret void
}

; REF-LABEL: define internal void @skip_atomic(
; REF-NEXT: store atomic i32 0, ptr %val
; REF-NEXT: ret void
define internal void @skip_atomic(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_atomic
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store atomic i32 0, ptr [[VAL]] seq_cst, align 4
; CHECK-NEXT:    ret void
;
  store atomic i32 0, ptr %val seq_cst, align 4
  ret void
}

define void @skip_atomic_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_atomic_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_atomic(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_atomic(ptr %val)
  ret void
}

; REF-LABEL: define internal void @skip_store_pointer_val(
; REF-NEXT: store ptr %val, i32** undef
; REF-NEXT: ret void
define internal void @skip_store_pointer_val(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_store_pointer_val
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store ptr [[VAL]], ptr undef, align 8
; CHECK-NEXT:    ret void
;
  store ptr %val, i32** undef
  ret void
}

define void @skip_store_pointer_val_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_store_pointer_val_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_store_pointer_val(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_store_pointer_val(ptr %val)
  ret void
}

; REF-LABEL: define internal void @skip_store_gep(
; REF-NEXT: %gep = getelementptr inbounds i32, ptr %val, i32 1
; REF-NEXT: store i32 0, ptr %gep
; REF-NEXT: ret void
define internal void @skip_store_gep(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_store_gep
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds i32, ptr [[VAL]], i32 1
; CHECK-NEXT:    store i32 0, ptr [[GEP]], align 4
; CHECK-NEXT:    ret void
;
  %gep = getelementptr inbounds i32, ptr %val, i32 1
  store i32 0, ptr %gep
  ret void
}

define void @skip_store_gep_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@skip_store_gep_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @skip_store_gep(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @skip_store_gep(ptr %val)
  ret void
}

; *** TODO: is this valid handling for sret?
; REF-LABEL: define internal void @skip_sret(i32* sret(i32) %sret, ptr %out) #0 {
; REF-NEXT: store
; REF-NEXT: store
; REF-NEXT: ret void
define internal void @skip_sret(i32* sret(i32) %sret, ptr %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@skip_sret
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[SKIP_SRET_RET0:%.*]] = insertvalue { i32, i32 } undef, i32 1, 0
; CHECK-NEXT:    [[SKIP_SRET_RET1:%.*]] = insertvalue { i32, i32 } [[SKIP_SRET_RET0]], i32 0, 1
; CHECK-NEXT:    ret { i32, i32 } [[SKIP_SRET_RET1]]
;
  store i32 1, ptr %sret
  store i32 0, ptr %out
  ret void
}

define void @skip_sret_caller(i32* sret(i32) %sret, ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@skip_sret_caller
; CHECK-SAME: (ptr sret(i32) [[SRET:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { i32, i32 } @skip_sret()
; CHECK-NEXT:    [[SRET_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 0
; CHECK-NEXT:    store i32 [[SRET_VAL_RET]], ptr [[SRET]], align 4
; CHECK-NEXT:    [[OUT_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 1
; CHECK-NEXT:    store i32 [[OUT_VAL_RET]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  call void @skip_sret(i32* sret(i32) %sret, ptr %out)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_i32_1_use @void_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %void_one_out_arg_i32_1_use zeroinitializer

; REF-LABEL: @void_one_out_arg_i32_1_use(
; REF-NEXT: %2 = call %void_one_out_arg_i32_1_use @void_one_out_arg_i32_1_use.body(i32* undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_i32_1_use %2, 0
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_1_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret i32 0
;
  store i32 0, ptr %val
  ret void
}

define void @void_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_1_use()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_1_use(ptr %val)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_i32_1_use_align @void_one_out_arg_i32_1_use_align.body(i32* align 8 %val) #0 {
; REF-NEXT: ret %void_one_out_arg_i32_1_use_align zeroinitializer

; REF-LABEL: @void_one_out_arg_i32_1_use_align(
; REF-NEXT: %2 = call %void_one_out_arg_i32_1_use_align @void_one_out_arg_i32_1_use_align.body(i32* undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_i32_1_use_align %2, 0
; REF-NEXT: store i32 %3, ptr %0, align 8
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_1_use_align(i32* align 8 %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_1_use_align
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret i32 0
;
  store i32 0, ptr %val, align 8
  ret void
}

define void @void_one_out_arg_i32_1_use_align_caller(i32* align 8 %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_1_use_align_caller
; CHECK-SAME: (ptr align 8 [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_1_use_align()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 8
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_1_use_align(i32* align 8 %val)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_i32_2_use @void_one_out_arg_i32_2_use.body(i1 %arg0, ptr %val) #0 {
; REF: br i1 %arg0, label %ret0, label %ret1

; REF: ret0:
; REF-NEXT: ret %void_one_out_arg_i32_2_use zeroinitializer

; REF: ret1:
; REF-NEXT: ret %void_one_out_arg_i32_2_use { i32 9 }

; REF-LABEL: define internal void @void_one_out_arg_i32_2_use(i1 %0, ptr %1) #2 {
; REF-NEXT: %3 = call %void_one_out_arg_i32_2_use @void_one_out_arg_i32_2_use.body(i1 %0, i32* undef)
; REF-NEXT: %4 = extractvalue %void_one_out_arg_i32_2_use %3, 0
; REF-NEXT: store i32 %4, ptr %1, align 4
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_2_use(i1 %arg0, ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_use
; CHECK-SAME: (i1 [[ARG0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    br i1 [[ARG0]], label [[RET0:%.*]], label [[RET1:%.*]]
; CHECK:       ret0:
; CHECK-NEXT:    ret i32 0
; CHECK:       ret1:
; CHECK-NEXT:    ret i32 9
;
  br i1 %arg0, label %ret0, label %ret1

ret0:
  store i32 0, ptr %val
  ret void

ret1:
  store i32 9, ptr %val
  ret void
}

define void @void_one_out_arg_i32_2_use_caller(i1 %arg0, ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_use_caller
; CHECK-SAME: (i1 [[ARG0:%.*]], ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_2_use(i1 [[ARG0]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_2_use(i1 %arg0, ptr %val)
  ret void
}

declare void @may.clobber()

; REF-LABEL: define private %void_one_out_arg_i32_2_stores @void_one_out_arg_i32_2_stores.body(ptr %val) #0 {
; REF-NEXT: store i32 0, ptr %val
; REF-NEXT: ret %void_one_out_arg_i32_2_stores { i32 1 }

; REF-LABEL: define internal void @void_one_out_arg_i32_2_stores(ptr %0) #2 {
; REF-NEXT: %2 = call %void_one_out_arg_i32_2_stores @void_one_out_arg_i32_2_stores.body(i32* undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_i32_2_stores %2, 0
; REF-NEXT: store i32 %3, ptr %0, align 4
define internal void @void_one_out_arg_i32_2_stores(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_stores
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret i32 1
;
  store i32 0, ptr %val
  store i32 1, ptr %val
  ret void
}

define void @void_one_out_arg_i32_2_stores_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_stores_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_2_stores()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_2_stores(ptr %val)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_i32_2_stores_clobber @void_one_out_arg_i32_2_stores_clobber.body(ptr %val) #0 {
; REF-NEXT: store i32 0, ptr %val
; REF-NEXT: call void @may.clobber()
; REF-NEXT: ret %void_one_out_arg_i32_2_stores_clobber { i32 1 }

; REF-LABEL: define internal void @void_one_out_arg_i32_2_stores_clobber(ptr %0) #2 {
; REF-NEXT: %2 = call %void_one_out_arg_i32_2_stores_clobber @void_one_out_arg_i32_2_stores_clobber.body(i32* undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_i32_2_stores_clobber %2, 0
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_2_stores_clobber(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_stores_clobber
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    call void @may.clobber()
; CHECK-NEXT:    ret i32 1
;
  store i32 0, ptr %val
  call void @may.clobber()
  store i32 1, ptr %val
  ret void
}

define void @void_one_out_arg_i32_2_stores_clobber_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_2_stores_clobber_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_2_stores_clobber()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_2_stores_clobber(ptr %val)
  ret void
}


; REF-LABEL: define internal void @void_one_out_arg_i32_call_may_clobber(ptr %val) #0 {
; REF-NEXT: store i32 0, ptr %val
; REF-NEXT: call void @may.clobber()
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_call_may_clobber(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_call_may_clobber
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store i32 0, ptr [[VAL]], align 4
; CHECK-NEXT:    call void @may.clobber()
; CHECK-NEXT:    ret void
;
  store i32 0, ptr %val
  call void @may.clobber()
  ret void
}

define void @void_one_out_arg_i32_call_may_clobber_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_call_may_clobber_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @void_one_out_arg_i32_call_may_clobber(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_call_may_clobber(ptr %val)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_i32_pre_call_may_clobber @void_one_out_arg_i32_pre_call_may_clobber.body(ptr %val) #0 {
; REF-NEXT: call void @may.clobber()
; REF-NEXT: ret %void_one_out_arg_i32_pre_call_may_clobber zeroinitializer

; REF-LABEL: @void_one_out_arg_i32_pre_call_may_clobber(ptr %0) #2 {
; REF-NEXT: %2 = call %void_one_out_arg_i32_pre_call_may_clobber @void_one_out_arg_i32_pre_call_may_clobber.body(i32* undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_i32_pre_call_may_clobber %2, 0
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_pre_call_may_clobber(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_pre_call_may_clobber
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    call void @may.clobber()
; CHECK-NEXT:    ret i32 0
;
  call void @may.clobber()
  store i32 0, ptr %val
  ret void
}

define void @void_one_out_arg_i32_pre_call_may_clobber_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_pre_call_may_clobber_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_pre_call_may_clobber()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_pre_call_may_clobber(ptr %val)
  ret void
}

; REF-LABEL: define internal void @void_one_out_arg_i32_reload(ptr %val) #0 {
; REF: store i32 0, ptr %val
; REF: %load = load i32, ptr %val, align 4
; REF: ret void
define internal void @void_one_out_arg_i32_reload(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_reload
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret i32 0
;
  store i32 0, ptr %val
  %load = load i32, ptr %val, align 4
  ret void
}

define void @void_one_out_arg_i32_reload_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_reload_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_reload()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_reload(ptr %val)
  ret void
}

; REF-LABEL: define internal void @void_one_out_arg_i32_store_in_different_block(
; REF-NEXT: %load = load i32, ptr addrspace(1) undef
; REF-NEXT: store i32 0, ptr %out
; REF-NEXT: br label %ret
; REF: ret:
; REF-NEXT: ret void
define internal void @void_one_out_arg_i32_store_in_different_block(ptr %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_store_in_different_block
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    br label [[RET:%.*]]
; CHECK:       ret:
; CHECK-NEXT:    ret i32 0
;
  %load = load i32, ptr addrspace(1) undef
  store i32 0, ptr %out
  br label %ret

ret:
  ret void
}

define void @void_one_out_arg_i32_store_in_different_block_caller(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_i32_store_in_different_block_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_arg_i32_store_in_different_block()
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_i32_store_in_different_block(ptr %out)
  ret void
}

; REF-LABEL: define internal void @unused_out_arg_one_branch(
; REF: ret0:
; REF-NEXT: ret void

; REF: ret1:
; REF-NEXT: store i32 9, ptr %val
; REF-NEXT: ret void
define internal void @unused_out_arg_one_branch(i1 %arg0, ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@unused_out_arg_one_branch
; CHECK-SAME: (i1 [[ARG0:%.*]], ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    br i1 [[ARG0]], label [[RET0:%.*]], label [[RET1:%.*]]
; CHECK:       ret0:
; CHECK-NEXT:    ret void
; CHECK:       ret1:
; CHECK-NEXT:    store i32 9, ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  br i1 %arg0, label %ret0, label %ret1

ret0:
  ret void

ret1:
  store i32 9, ptr %val
  ret void
}

define void @unused_out_arg_one_branch_caller(i1 %arg0, ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@unused_out_arg_one_branch_caller
; CHECK-SAME: (i1 [[ARG0:%.*]], ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @unused_out_arg_one_branch(i1 [[ARG0]], ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @unused_out_arg_one_branch(i1 %arg0, ptr %val)
  ret void
}

; REF-LABEL: define private %void_one_out_arg_v2i32_1_use @void_one_out_arg_v2i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %void_one_out_arg_v2i32_1_use { <2 x i32> <i32 17, i32 9> }

; REF-LABEL: define internal void @void_one_out_arg_v2i32_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %void_one_out_arg_v2i32_1_use @void_one_out_arg_v2i32_1_use.body(ptr undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_v2i32_1_use %2, 0
; REF-NEXT: store <2 x i32> %3, ptr %0, align 8
; REF-NEXT: ret void
define internal void @void_one_out_arg_v2i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_v2i32_1_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret <2 x i32> <i32 17, i32 9>
;
  store <2 x i32> <i32 17, i32 9>, ptr %val
  ret void
}

define void @void_one_out_arg_v2i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_v2i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @void_one_out_arg_v2i32_1_use()
; CHECK-NEXT:    store <2 x i32> [[TMP1]], ptr [[VAL]], align 8
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_v2i32_1_use(ptr %val)
  ret void
}

%struct = type { i32, i8, float }

; *** TODO: this should be handled as well
; REF-LABEL: define private %void_one_out_arg_struct_1_use @void_one_out_arg_struct_1_use.body(ptr %out) #0 {
; REF-NEXT: ret %void_one_out_arg_struct_1_use { %struct { i32 9, i8 99, float 4.000000e+00 } }

; Normally this is split into element accesses which we don't handle.
; REF-LABEL: define internal void @void_one_out_arg_struct_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %void_one_out_arg_struct_1_use @void_one_out_arg_struct_1_use.body(ptr undef)
; REF-NEXT: %3 = extractvalue %void_one_out_arg_struct_1_use %2, 0
; REF-NEXT: store %struct %3, ptr %0, align 4
; REF-NEXT: ret void
define internal void @void_one_out_arg_struct_1_use(ptr %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_struct_1_use
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store [[STRUCT:%.*]] { i32 9, i8 99, float 4.000000e+00 }, ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  store %struct { i32 9, i8 99, float 4.0 }, ptr %out
  ret void
}

define void @void_one_out_arg_struct_1_use_caller(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_arg_struct_1_use_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @void_one_out_arg_struct_1_use(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @void_one_out_arg_struct_1_use(ptr %out)
  ret void
}

; REF-LABEL: define private %i32_one_out_arg_i32_1_use @i32_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %i32_one_out_arg_i32_1_use { i32 9, i32 24 }

; REF-LABEL: define internal i32 @i32_one_out_arg_i32_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %i32_one_out_arg_i32_1_use @i32_one_out_arg_i32_1_use.body(i32* undef)
; REF-NEXT: %3 = extractvalue %i32_one_out_arg_i32_1_use %2, 1
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: %4 = extractvalue %i32_one_out_arg_i32_1_use %2, 0
; REF-NEXT: ret i32 %4
define internal i32 @i32_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@i32_one_out_arg_i32_1_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[I32_ONE_OUT_ARG_I32_1_USE_RET:%.*]] = insertvalue { i32, i32 } undef, i32 9, 0
; CHECK-NEXT:    [[I32_ONE_OUT_ARG_I32_1_USE_RET1:%.*]] = insertvalue { i32, i32 } [[I32_ONE_OUT_ARG_I32_1_USE_RET]], i32 24, 1
; CHECK-NEXT:    ret { i32, i32 } [[I32_ONE_OUT_ARG_I32_1_USE_RET1]]
;
  store i32 24, ptr %val
  ret i32 9
}

define i32 @i32_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@i32_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { i32, i32 } @i32_one_out_arg_i32_1_use()
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { i32, i32 } [[R]], 0
; CHECK-NEXT:    [[VAL_VAL_RET:%.*]] = extractvalue { i32, i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[VAL_VAL_RET]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret i32 [[R_RET]]
;
  %R = call i32 @i32_one_out_arg_i32_1_use(ptr %val)
  ret i32 %R
}

; REF-LABEL: define private %unused_different_type @unused_different_type.body(ptr %arg0, float* nocapture %arg1) #0 {
; REF-NEXT: ret %unused_different_type { float 4.000000e+00 }

; REF-LABEL: define internal void @unused_different_type(ptr %0, float* nocapture %1) #2 {
; REF-NEXT: %3 = call %unused_different_type @unused_different_type.body(ptr %0, float* undef)
; REF-NEXT: %4 = extractvalue %unused_different_type %3, 0
; REF-NEXT: store float %4, float* %1, align 4
; REF-NEXT: ret void
define internal void @unused_different_type(ptr %arg0, float* nocapture %arg1) #0 {
; CHECK-LABEL: define {{[^@]+}}@unused_different_type
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret float 4.000000e+00
;
  store float 4.0, float* %arg1, align 4
  ret void
}

define void @unused_different_type_caller(ptr %arg0, float* nocapture %arg1) {
; CHECK-LABEL: define {{[^@]+}}@unused_different_type_caller
; CHECK-SAME: (ptr [[ARG0:%.*]], ptr captures(none) [[ARG1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call float @unused_different_type()
; CHECK-NEXT:    store float [[TMP1]], ptr [[ARG1]], align 4
; CHECK-NEXT:    ret void
;
  call void @unused_different_type(ptr %arg0, float* nocapture %arg1)
  ret void
}

; REF-LABEL: define private %multiple_same_return_noalias @multiple_same_return_noalias.body(i32* noalias %out0, i32* noalias %out1) #0 {
; REF-NEXT: ret %multiple_same_return_noalias { i32 1, i32 2 }

; REF-LABEL: define internal void @multiple_same_return_noalias(
; REF-NEXT: %3 = call %multiple_same_return_noalias @multiple_same_return_noalias.body(i32* undef, i32* undef)
; REF-NEXT: %4 = extractvalue %multiple_same_return_noalias %3, 0
; REF-NEXT: store i32 %4, ptr %0, align 4
; REF-NEXT: %5 = extractvalue %multiple_same_return_noalias %3, 1
; REF-NEXT: store i32 %5, ptr %1, align 4
; REF-NEXT: ret void
define internal void @multiple_same_return_noalias(i32* noalias %out0, i32* noalias %out1) #0 {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_noalias
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_NOALIAS_RET0:%.*]] = insertvalue { i32, i32 } undef, i32 1, 0
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_NOALIAS_RET1:%.*]] = insertvalue { i32, i32 } [[MULTIPLE_SAME_RETURN_NOALIAS_RET0]], i32 2, 1
; CHECK-NEXT:    ret { i32, i32 } [[MULTIPLE_SAME_RETURN_NOALIAS_RET1]]
;
  store i32 1, ptr %out0, align 4
  store i32 2, ptr %out1, align 4
  ret void
}

define void @multiple_same_return_noalias_caller(i32* noalias %out0, i32* noalias %out1) {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_noalias_caller
; CHECK-SAME: (ptr noalias [[OUT0:%.*]], ptr noalias [[OUT1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { i32, i32 } @multiple_same_return_noalias()
; CHECK-NEXT:    [[OUT1_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 1
; CHECK-NEXT:    store i32 [[OUT1_VAL_RET]], ptr [[OUT1]], align 4
; CHECK-NEXT:    [[OUT0_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 0
; CHECK-NEXT:    store i32 [[OUT0_VAL_RET]], ptr [[OUT0]], align 4
; CHECK-NEXT:    ret void
;
  call void @multiple_same_return_noalias(i32* noalias %out0, i32* noalias %out1)
  ret void
}

; REF-LABEL: define private %multiple_same_return_mayalias @multiple_same_return_mayalias.body(ptr %out0, ptr %out1) #0 {
; REF-NEXT: ret %multiple_same_return_mayalias { i32 2, i32 1 }

; REF-LABEL: define internal void @multiple_same_return_mayalias(ptr %0, ptr %1) #2 {
; REF-NEXT: %3 = call %multiple_same_return_mayalias @multiple_same_return_mayalias.body(i32* undef, i32* undef)
; REF-NEXT: %4 = extractvalue %multiple_same_return_mayalias %3, 0
; REF-NEXT: store i32 %4, ptr %0, align 4
; REF-NEXT: %5 = extractvalue %multiple_same_return_mayalias %3, 1
; REF-NEXT: store i32 %5, ptr %1, align 4
; REF-NEXT: ret void
define internal void @multiple_same_return_mayalias(ptr %out0, ptr %out1) #0 {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_mayalias
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_MAYALIAS_RET0:%.*]] = insertvalue { i32, i32 } undef, i32 1, 0
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_MAYALIAS_RET1:%.*]] = insertvalue { i32, i32 } [[MULTIPLE_SAME_RETURN_MAYALIAS_RET0]], i32 2, 1
; CHECK-NEXT:    ret { i32, i32 } [[MULTIPLE_SAME_RETURN_MAYALIAS_RET1]]
;
  store i32 1, ptr %out0, align 4
  store i32 2, ptr %out1, align 4
  ret void
}

define void @multiple_same_return_mayalias_caller(ptr %out0, ptr %out1) {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_mayalias_caller
; CHECK-SAME: (ptr [[OUT0:%.*]], ptr [[OUT1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { i32, i32 } @multiple_same_return_mayalias()
; CHECK-NEXT:    [[OUT0_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 0
; CHECK-NEXT:    store i32 [[OUT0_VAL_RET]], ptr [[OUT0]], align 4
; CHECK-NEXT:    [[OUT1_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 1
; CHECK-NEXT:    store i32 [[OUT1_VAL_RET]], ptr [[OUT1]], align 4
; CHECK-NEXT:    ret void
;
  call void @multiple_same_return_mayalias(ptr %out0, ptr %out1)
  ret void
}

; REF-LABEL: define private %multiple_same_return_mayalias_order @multiple_same_return_mayalias_order.body(ptr %out0, ptr %out1) #0 {
; REF-NEXT: ret %multiple_same_return_mayalias_order { i32 1, i32 2 }

; REF-LABEL: define internal void @multiple_same_return_mayalias_order(ptr %0, ptr %1) #2 {
; REF-NEXT: %3 = call %multiple_same_return_mayalias_order @multiple_same_return_mayalias_order.body(i32* undef, i32* undef)
; REF-NEXT: %4 = extractvalue %multiple_same_return_mayalias_order %3, 0
; REF-NEXT: store i32 %4, ptr %0, align 4
; REF-NEXT: %5 = extractvalue %multiple_same_return_mayalias_order %3, 1
; REF-NEXT: store i32 %5, ptr %1, align 4
; REF-NEXT: ret void
define internal void @multiple_same_return_mayalias_order(ptr %out0, ptr %out1) #0 {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_mayalias_order
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_MAYALIAS_ORDER_RET0:%.*]] = insertvalue { i32, i32 } undef, i32 1, 0
; CHECK-NEXT:    [[MULTIPLE_SAME_RETURN_MAYALIAS_ORDER_RET1:%.*]] = insertvalue { i32, i32 } [[MULTIPLE_SAME_RETURN_MAYALIAS_ORDER_RET0]], i32 2, 1
; CHECK-NEXT:    ret { i32, i32 } [[MULTIPLE_SAME_RETURN_MAYALIAS_ORDER_RET1]]
;
  store i32 2, ptr %out1, align 4
  store i32 1, ptr %out0, align 4
  ret void
}

define void @multiple_same_return_mayalias_order_caller(ptr %out0, ptr %out1) {
; CHECK-LABEL: define {{[^@]+}}@multiple_same_return_mayalias_order_caller
; CHECK-SAME: (ptr [[OUT0:%.*]], ptr [[OUT1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { i32, i32 } @multiple_same_return_mayalias_order()
; CHECK-NEXT:    [[OUT1_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 1
; CHECK-NEXT:    store i32 [[OUT1_VAL_RET]], ptr [[OUT1]], align 4
; CHECK-NEXT:    [[OUT0_VAL_RET:%.*]] = extractvalue { i32, i32 } [[TMP1]], 0
; CHECK-NEXT:    store i32 [[OUT0_VAL_RET]], ptr [[OUT0]], align 4
; CHECK-NEXT:    ret void
;
  call void @multiple_same_return_mayalias_order(ptr %out0, ptr %out1)
  ret void
}

; Currently this fails to convert because the store won't be found if
; it isn't in the same block as the return.
; REF-LABEL: define internal i32 @store_in_entry_block(i1 %arg0, ptr %out) #0 {
; REF-NOT: call
define internal i32 @store_in_entry_block(i1 %arg0, ptr %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@store_in_entry_block
; CHECK-SAME: (i1 [[ARG0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[VAL0:%.*]] = load i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    br i1 [[ARG0]], label [[IF:%.*]], label [[ENDIF:%.*]]
; CHECK:       if:
; CHECK-NEXT:    [[VAL1:%.*]] = load i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    br label [[ENDIF]]
; CHECK:       endif:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[VAL1]], [[IF]] ]
; CHECK-NEXT:    [[STORE_IN_ENTRY_BLOCK_ENDIF_RET:%.*]] = insertvalue { i32, i32 } undef, i32 [[PHI]], 0
; CHECK-NEXT:    [[STORE_IN_ENTRY_BLOCK_ENDIF_RET1:%.*]] = insertvalue { i32, i32 } [[STORE_IN_ENTRY_BLOCK_ENDIF_RET]], i32 [[VAL0]], 1
; CHECK-NEXT:    ret { i32, i32 } [[STORE_IN_ENTRY_BLOCK_ENDIF_RET1]]
;
entry:
  %val0 = load i32, ptr addrspace(1) undef
  store i32 %val0, ptr %out
  br i1 %arg0, label %if, label %endif

if:
  %val1 = load i32, ptr addrspace(1) undef
  br label %endif

endif:
  %phi = phi i32 [ 0, %entry ], [ %val1, %if ]
  ret i32 %phi
}

define i32 @store_in_entry_block_caller(i1 %arg0, ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@store_in_entry_block_caller
; CHECK-SAME: (i1 [[ARG0:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { i32, i32 } @store_in_entry_block(i1 [[ARG0]])
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { i32, i32 } [[R]], 0
; CHECK-NEXT:    [[OUT_VAL_RET:%.*]] = extractvalue { i32, i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[OUT_VAL_RET]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret i32 [[R_RET]]
;
  %R = call i32 @store_in_entry_block(i1 %arg0, ptr %out)
  ret i32 %R
}

; REF-LABEL: define private %i1_one_out_arg_i32_1_use @i1_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %i1_one_out_arg_i32_1_use { i1 true, i32 24 }

; REF-LABEL: define internal i1 @i1_one_out_arg_i32_1_use(ptr %0) #2 {
; REF: %2 = call %i1_one_out_arg_i32_1_use @i1_one_out_arg_i32_1_use.body(i32* undef)
; REF: %3 = extractvalue %i1_one_out_arg_i32_1_use %2, 1
; REF: store i32 %3, ptr %0, align 4
; REF: %4 = extractvalue %i1_one_out_arg_i32_1_use %2, 0
; REF: ret i1 %4
define internal i1 @i1_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@i1_one_out_arg_i32_1_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[I1_ONE_OUT_ARG_I32_1_USE_RET:%.*]] = insertvalue { i1, i32 } undef, i1 true, 0
; CHECK-NEXT:    [[I1_ONE_OUT_ARG_I32_1_USE_RET1:%.*]] = insertvalue { i1, i32 } [[I1_ONE_OUT_ARG_I32_1_USE_RET]], i32 24, 1
; CHECK-NEXT:    ret { i1, i32 } [[I1_ONE_OUT_ARG_I32_1_USE_RET1]]
;
  store i32 24, ptr %val
  ret i1 true
}

define i1 @i1_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@i1_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { i1, i32 } @i1_one_out_arg_i32_1_use()
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { i1, i32 } [[R]], 0
; CHECK-NEXT:    [[VAL_VAL_RET:%.*]] = extractvalue { i1, i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[VAL_VAL_RET]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret i1 [[R_RET]]
;
  %R = call i1 @i1_one_out_arg_i32_1_use(ptr %val)
  ret i1 %R
}

; *** MSSA pass just refuses to promote if return values has attribute
; Make sure we don't leave around return attributes that are
; incompatible with struct return types.

; REF-LABEL: define private %i1_zeroext_one_out_arg_i32_1_use @i1_zeroext_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %i1_zeroext_one_out_arg_i32_1_use { i1 true, i32 24 }

; REF-LABEL: define zeroext i1 @i1_zeroext_one_out_arg_i32_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %i1_zeroext_one_out_arg_i32_1_use @i1_zeroext_one_out_arg_i32_1_use.body(i32* undef)
; REF-NEXT: %3 = extractvalue %i1_zeroext_one_out_arg_i32_1_use %2, 1
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: %4 = extractvalue %i1_zeroext_one_out_arg_i32_1_use %2, 0
; REF-NEXT: ret i1 %4
define internal zeroext i1 @i1_zeroext_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@i1_zeroext_one_out_arg_i32_1_use
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store i32 24, ptr [[VAL]], align 4
; CHECK-NEXT:    ret i1 true
;
  store i32 24, ptr %val
  ret i1 true
}

define zeroext i1 @i1_zeroext_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@i1_zeroext_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call zeroext i1 @i1_zeroext_one_out_arg_i32_1_use(ptr [[VAL]])
; CHECK-NEXT:    ret i1 [[R]]
;
  %R = call zeroext i1 @i1_zeroext_one_out_arg_i32_1_use(ptr %val)
  ret i1 %R
}

; *** The same as previous
; REF-LABEL: define private %i1_signext_one_out_arg_i32_1_use @i1_signext_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %i1_signext_one_out_arg_i32_1_use { i1 true, i32 24 }

; REF-LABEL: define signext i1 @i1_signext_one_out_arg_i32_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %i1_signext_one_out_arg_i32_1_use @i1_signext_one_out_arg_i32_1_use.body(i32* undef)
; REF-NEXT: %3 = extractvalue %i1_signext_one_out_arg_i32_1_use %2, 1
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: %4 = extractvalue %i1_signext_one_out_arg_i32_1_use %2, 0
; REF-NEXT: ret i1 %4
define internal signext i1 @i1_signext_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@i1_signext_one_out_arg_i32_1_use
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store i32 24, ptr [[VAL]], align 4
; CHECK-NEXT:    ret i1 true
;
  store i32 24, ptr %val
  ret i1 true
}

define signext i1 @i1_signext_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@i1_signext_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call signext i1 @i1_signext_one_out_arg_i32_1_use(ptr [[VAL]])
; CHECK-NEXT:    ret i1 [[R]]
;
  %R = call signext i1 @i1_signext_one_out_arg_i32_1_use(ptr %val)
  ret i1 %R
}

; *** The same as previous
; REF-LABEL: define private %p1i32_noalias_one_out_arg_i32_1_use @p1i32_noalias_one_out_arg_i32_1_use.body(ptr %val) #0 {
; REF-NEXT: ret %p1i32_noalias_one_out_arg_i32_1_use { ptr addrspace(1) null, i32 24 }

; REF-LABEL: define noalias ptr addrspace(1) @p1i32_noalias_one_out_arg_i32_1_use(ptr %0) #2 {
; REF-NEXT: %2 = call %p1i32_noalias_one_out_arg_i32_1_use @p1i32_noalias_one_out_arg_i32_1_use.body(i32* undef)
; REF-NEXT: %3 = extractvalue %p1i32_noalias_one_out_arg_i32_1_use %2, 1
; REF-NEXT: store i32 %3, ptr %0, align 4
; REF-NEXT: %4 = extractvalue %p1i32_noalias_one_out_arg_i32_1_use %2, 0
; REF-NEXT: ret ptr addrspace(1) %4
define internal noalias ptr addrspace(1) @p1i32_noalias_one_out_arg_i32_1_use(ptr %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@p1i32_noalias_one_out_arg_i32_1_use
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store i32 24, ptr [[VAL]], align 4
; CHECK-NEXT:    ret ptr addrspace(1) null
;
  store i32 24, ptr %val
  ret ptr addrspace(1) null
}

define noalias ptr addrspace(1) @p1i32_noalias_one_out_arg_i32_1_use_caller(ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@p1i32_noalias_one_out_arg_i32_1_use_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call noalias ptr addrspace(1) @p1i32_noalias_one_out_arg_i32_1_use(ptr [[VAL]])
; CHECK-NEXT:    ret ptr addrspace(1) [[R]]
;
  %R = call noalias ptr addrspace(1) @p1i32_noalias_one_out_arg_i32_1_use(ptr %val)
  ret ptr addrspace(1) %R
}

; *** don't know why it wasn't handled before
; REF-LABEL: define internal void @void_one_out_non_private_arg_i32_1_use(ptr addrspace(1) %val) #0 {
; REF-NEXT: store i32 0, ptr addrspace(1) %val
; REF-NEXT: ret void
define internal void @void_one_out_non_private_arg_i32_1_use(ptr addrspace(1) %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_non_private_arg_i32_1_use
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    ret i32 0
;
  store i32 0, ptr addrspace(1) %val
  ret void
}

define void @void_one_out_non_private_arg_i32_1_use_caller(ptr addrspace(1) %val) {
; CHECK-LABEL: define {{[^@]+}}@void_one_out_non_private_arg_i32_1_use_caller
; CHECK-SAME: (ptr addrspace(1) [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @void_one_out_non_private_arg_i32_1_use()
; CHECK-NEXT:    store i32 [[TMP1]], ptr addrspace(1) [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @void_one_out_non_private_arg_i32_1_use(ptr addrspace(1) %val)
  ret void
}

; REF-LABEL: define private %func_ptr_type @func_ptr_type.body(void ()** %out) #0 {
; REF-LABEL: define internal void @func_ptr_type(void ()** %0) #2 {
; REF: %2 = call %func_ptr_type @func_ptr_type.body(void ()** undef)
define internal void @func_ptr_type(void()** %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@func_ptr_type
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:    [[FUNC:%.*]] = load ptr, ptr undef, align 8
; CHECK-NEXT:    ret ptr [[FUNC]]
;
  %func = load void()*, void()** undef
  store void()* %func, void()** %out
  ret void
}

define void @func_ptr_type_caller(void()** %out) {
; CHECK-LABEL: define {{[^@]+}}@func_ptr_type_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @func_ptr_type()
; CHECK-NEXT:    store ptr [[TMP1]], ptr [[OUT]], align 8
; CHECK-NEXT:    ret void
;
  call void @func_ptr_type(void()** %out)
  ret void
}

; *** TODO: bitcasts not supported yet
; REF-LABEL: define private %bitcast_func_ptr_type @bitcast_func_ptr_type.body(void ()** %out) #0 {
; REF-LABEL: define internal void @bitcast_func_ptr_type(void ()** %0) #2 {
define internal void @bitcast_func_ptr_type(void()** %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_func_ptr_type
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[FUNC:%.*]] = load ptr, ptr undef, align 8
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store ptr [[FUNC]], ptr [[CAST]], align 8
; CHECK-NEXT:    ret void
;
  %func = load i32()*, i32()** undef
  %cast = bitcast void()** %out to i32()**
  store i32()* %func, i32()** %cast
  ret void
}

define void @bitcast_func_ptr_type_caller(void()** %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_func_ptr_type_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_func_ptr_type(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_func_ptr_type(void()** %out)
  ret void
}

; *** TODO: rettype not supported yet
; REF-LABEL: define private %out_arg_small_array @out_arg_small_array.body([4 x i32]* %val) #0 {
; REF-NEXT: ret %out_arg_small_array { [4 x i32] [i32 0, i32 1, i32 2, i32 3] }
; REF-LABEL: define internal void @out_arg_small_array([4 x i32]* %0) #2 {
define internal void @out_arg_small_array([4 x i32]* %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@out_arg_small_array
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store [4 x i32] [i32 0, i32 1, i32 2, i32 3], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  store [4 x i32] [i32 0, i32 1, i32 2, i32 3], [4 x i32]* %val
  ret void
}

define void @out_arg_small_array_caller([4 x i32]* %val) {
; CHECK-LABEL: define {{[^@]+}}@out_arg_small_array_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @out_arg_small_array(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @out_arg_small_array([4 x i32]* %val)
  ret void
}

; *** TODO: check if the behaviour is the same, when the prev testcase is done
; REF-LABEL: define internal void @out_arg_large_array([17 x i32]* %val) #0 {
; REF-NEXT: store [17 x i32] zeroinitializer, [17 x i32]* %val
; REF-NEXT: ret void
define internal void @out_arg_large_array([17 x i32]* %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@out_arg_large_array
; CHECK-SAME: (ptr [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    store [17 x i32] zeroinitializer, ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  store [17 x i32] zeroinitializer, [17 x i32]* %val
  ret void
}

define void @out_arg_large_array_caller([17 x i32]* %val) {
; CHECK-LABEL: define {{[^@]+}}@out_arg_large_array_caller
; CHECK-SAME: (ptr [[VAL:%.*]]) {
; CHECK-NEXT:    call void @out_arg_large_array(ptr [[VAL]])
; CHECK-NEXT:    ret void
;
  call void @out_arg_large_array([17 x i32]* %val)
  ret void
}

; *** different: no checks on register usage yet
; REF-LABEL: define <16 x i32> @num_regs_return_limit(ptr %out, i32 %val) #0 {
define internal <16 x i32> @num_regs_return_limit(ptr %out, i32 %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@num_regs_return_limit
; CHECK-SAME: (i32 [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile <16 x i32>, ptr addrspace(1) undef, align 64
; CHECK-NEXT:    [[NUM_REGS_RETURN_LIMIT_RET:%.*]] = insertvalue { <16 x i32>, i32 } undef, <16 x i32> [[LOAD]], 0
; CHECK-NEXT:    [[NUM_REGS_RETURN_LIMIT_RET1:%.*]] = insertvalue { <16 x i32>, i32 } [[NUM_REGS_RETURN_LIMIT_RET]], i32 [[VAL]], 1
; CHECK-NEXT:    ret { <16 x i32>, i32 } [[NUM_REGS_RETURN_LIMIT_RET1]]
;
  %load = load volatile <16 x i32>, <16 x i32> addrspace(1)* undef
  store i32 %val, ptr %out
  ret <16 x i32> %load
}

define <16 x i32> @num_regs_return_limit_caller(ptr %out, i32 %val) {
; CHECK-LABEL: define {{[^@]+}}@num_regs_return_limit_caller
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { <16 x i32>, i32 } @num_regs_return_limit(i32 [[VAL]])
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { <16 x i32>, i32 } [[R]], 0
; CHECK-NEXT:    [[OUT_VAL_RET:%.*]] = extractvalue { <16 x i32>, i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[OUT_VAL_RET]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret <16 x i32> [[R_RET]]
;
  %R = call <16 x i32> @num_regs_return_limit(ptr %out, i32 %val)
  ret <16 x i32> %R
}

; *** different: no checks on register usage yet
; REF-LABEL: define private %num_regs_reach_limit @num_regs_reach_limit.body(ptr %out, i32 %val) #0 {
; REF: define [15 x i32] @num_regs_reach_limit(ptr %0, i32 %1) #2 {
; REF-NEXT: call %num_regs_reach_limit @num_regs_reach_limit.body(i32* undef, i32 %1)
define internal [15 x i32] @num_regs_reach_limit(ptr %out, i32 %val) #0 {
; CHECK-LABEL: define {{[^@]+}}@num_regs_reach_limit
; CHECK-SAME: (i32 [[VAL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile [15 x i32], ptr addrspace(1) undef, align 4
; CHECK-NEXT:    [[NUM_REGS_REACH_LIMIT_RET:%.*]] = insertvalue { [15 x i32], i32 } undef, [15 x i32] [[LOAD]], 0
; CHECK-NEXT:    [[NUM_REGS_REACH_LIMIT_RET1:%.*]] = insertvalue { [15 x i32], i32 } [[NUM_REGS_REACH_LIMIT_RET]], i32 [[VAL]], 1
; CHECK-NEXT:    ret { [15 x i32], i32 } [[NUM_REGS_REACH_LIMIT_RET1]]
;
  %load = load volatile [15 x i32], [15 x i32] addrspace(1)* undef
  store i32 %val, ptr %out
  ret [15 x i32] %load
}

define [15 x i32] @num_regs_reach_limit_caller(ptr %out, i32 %val) {
; CHECK-LABEL: define {{[^@]+}}@num_regs_reach_limit_caller
; CHECK-SAME: (ptr [[OUT:%.*]], i32 [[VAL:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { [15 x i32], i32 } @num_regs_reach_limit(i32 [[VAL]])
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { [15 x i32], i32 } [[R]], 0
; CHECK-NEXT:    [[OUT_VAL_RET:%.*]] = extractvalue { [15 x i32], i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[OUT_VAL_RET]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret [15 x i32] [[R_RET]]
;
  %R = call [15 x i32] @num_regs_reach_limit(ptr %out, i32 %val)
  ret [15 x i32] %R
}

; *** different: no checks on register usage yet
; REF-LABEL: define private %num_regs_reach_limit_leftover @num_regs_reach_limit_leftover.body(ptr %out0, ptr %out1, i32 %val0) #0 {
; REF-NEXT: %load0 = load volatile [15 x i32], [15 x i32] addrspace(1)* undef
; REF-NEXT: %load1 = load volatile i32, ptr addrspace(1) undef
; REF-NEXT: %1 = insertvalue %num_regs_reach_limit_leftover undef, [15 x i32] %load0, 0
; REF-NEXT: %2 = insertvalue %num_regs_reach_limit_leftover %1, i32 %load1, 1
; REF-NEXT: %3 = insertvalue %num_regs_reach_limit_leftover %2, i32 %val0, 2
; REF-NEXT: ret %num_regs_reach_limit_leftover %3

; REF-LABEL: define [15 x i32] @num_regs_reach_limit_leftover(ptr %0, ptr %1, i32 %2) #2 {
; REF-NEXT: %4 = call %num_regs_reach_limit_leftover @num_regs_reach_limit_leftover.body(i32* undef, i32* undef, i32 %2)
; REF-NEXT: %5 = extractvalue %num_regs_reach_limit_leftover %4, 1
; REF-NEXT: store i32 %5, ptr %0, align 4
; REF-NEXT: %6 = extractvalue %num_regs_reach_limit_leftover %4, 2
; REF-NEXT: store i32 %6, ptr %1, align 4
; REF-NEXT: %7 = extractvalue %num_regs_reach_limit_leftover %4, 0
; REF-NEXT: ret [15 x i32] %7
define internal [15 x i32] @num_regs_reach_limit_leftover(ptr %out0, ptr %out1, i32 %val0) #0 {
; CHECK-LABEL: define {{[^@]+}}@num_regs_reach_limit_leftover
; CHECK-SAME: (i32 [[VAL0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD0:%.*]] = load volatile [15 x i32], ptr addrspace(1) undef, align 4
; CHECK-NEXT:    [[LOAD1:%.*]] = load volatile i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET:%.*]] = insertvalue { [15 x i32], i32, i32 } undef, [15 x i32] [[LOAD0]], 0
; CHECK-NEXT:    [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET1:%.*]] = insertvalue { [15 x i32], i32, i32 } [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET]], i32 [[VAL0]], 1
; CHECK-NEXT:    [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET2:%.*]] = insertvalue { [15 x i32], i32, i32 } [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET1]], i32 [[LOAD1]], 2
; CHECK-NEXT:    ret { [15 x i32], i32, i32 } [[NUM_REGS_REACH_LIMIT_LEFTOVER_RET2]]
;
  %load0 = load volatile [15 x i32], [15 x i32] addrspace(1)* undef
  %load1 = load volatile i32, ptr addrspace(1) undef
  store i32 %val0, ptr %out0
  store i32 %load1, ptr %out1
  ret [15 x i32] %load0
}

define [15 x i32] @num_regs_reach_limit_leftover_caller(ptr %out0, ptr %out1, i32 %val0) {
; CHECK-LABEL: define {{[^@]+}}@num_regs_reach_limit_leftover_caller
; CHECK-SAME: (ptr [[OUT0:%.*]], ptr [[OUT1:%.*]], i32 [[VAL0:%.*]]) {
; CHECK-NEXT:    [[R:%.*]] = call { [15 x i32], i32, i32 } @num_regs_reach_limit_leftover(i32 [[VAL0]])
; CHECK-NEXT:    [[R_RET:%.*]] = extractvalue { [15 x i32], i32, i32 } [[R]], 0
; CHECK-NEXT:    [[OUT0_VAL_RET:%.*]] = extractvalue { [15 x i32], i32, i32 } [[R]], 1
; CHECK-NEXT:    store i32 [[OUT0_VAL_RET]], ptr [[OUT0]], align 4
; CHECK-NEXT:    [[OUT1_VAL_RET:%.*]] = extractvalue { [15 x i32], i32, i32 } [[R]], 2
; CHECK-NEXT:    store i32 [[OUT1_VAL_RET]], ptr [[OUT1]], align 4
; CHECK-NEXT:    ret [15 x i32] [[R_RET]]
;
  %R = call [15 x i32] @num_regs_reach_limit_leftover(ptr %out0, ptr %out1, i32 %val0)
  ret [15 x i32] %R
}

; *** TODO: preserve debug info
; REF-LABEL: define private %preserve_debug_info @preserve_debug_info.body(i32 %arg0, ptr %val) #0 {
; REF-NEXT: call void @may.clobber(), !dbg !5
; REF-NEXT: %1 = insertvalue %preserve_debug_info undef, i32 %arg0, 0, !dbg !11
; REF-NEXT: ret %preserve_debug_info %1, !dbg !11

; REF-LABEL: define internal void @preserve_debug_info(i32 %0, ptr %1) #2 !dbg !6 {
; REF-NEXT: %3 = call %preserve_debug_info @preserve_debug_info.body(i32 %0, i32* undef){{$}}
; REF-NEXT: %4 = extractvalue %preserve_debug_info %3, 0{{$}}
; REF-NEXT: store i32 %4, ptr %1, align 4{{$}}
; REF-NEXT: ret void
define internal void @preserve_debug_info(i32 %arg0, ptr %val) #0 !dbg !5 {
; CHECK-LABEL: define {{[^@]+}}@preserve_debug_info
; CHECK-SAME: (i32 [[ARG0:%.*]]) #[[ATTR0]] !dbg [[DBG5:![0-9]+]] {
; CHECK-NEXT:    call void @may.clobber(), !dbg [[DBG10:![0-9]+]]
; CHECK-NEXT:    ret i32 [[ARG0]]
;
  call void @may.clobber(), !dbg !10
  store i32 %arg0, ptr %val, !dbg !11
  ret void, !dbg !12
}

define void @preserve_debug_info_caller(i32 %arg0, ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@preserve_debug_info_caller
; CHECK-SAME: (i32 [[ARG0:%.*]], ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @preserve_debug_info(i32 [[ARG0]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @preserve_debug_info(i32 %arg0, ptr %val)
  ret void
}

define internal void @preserve_metadata(i32 %arg0, ptr %val) #0 !kernel_arg_access_qual !13 {
; CHECK-LABEL: define {{[^@]+}}@preserve_metadata
; CHECK-SAME: (i32 [[ARG0:%.*]]) #[[ATTR0]] {{.*}}{
; CHECK-NEXT:    call void @may.clobber()
; CHECK-NEXT:    ret i32 [[ARG0]]
;
  call void @may.clobber()
  store i32 %arg0, ptr %val
  ret void
}

define void @preserve_metadata_caller(i32 %arg0, ptr %val) {
; CHECK-LABEL: define {{[^@]+}}@preserve_metadata_caller
; CHECK-SAME: (i32 [[ARG0:%.*]], ptr [[VAL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @preserve_metadata(i32 [[ARG0]])
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[VAL]], align 4
; CHECK-NEXT:    ret void
;
  call void @preserve_metadata(i32 %arg0, ptr %val)
  ret void
}

; *** TODO: bitcast support
; Clang emits this pattern for 3-vectors for some reason.
; REF-LABEL: define private %bitcast_pointer_v4i32_v3i32 @bitcast_pointer_v4i32_v3i32.body(<3 x i32>* %out) #0 {
; REF-NEXT: %load = load volatile <4 x i32>, <4 x i32> addrspace(1)* undef
; REF-NEXT: %bitcast = bitcast <3 x i32>* %out to <4 x i32>*
; REF-NEXT: %1 = shufflevector <4 x i32> %load, <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
; REF-NEXT: %2 = insertvalue %bitcast_pointer_v4i32_v3i32 undef, <3 x i32> %1, 0
; REF-NEXT: ret %bitcast_pointer_v4i32_v3i32 %2

; REF-LABEL: define internal void @bitcast_pointer_v4i32_v3i32(<3 x i32>* %0) #2 {
; REF-NEXT: %2 = call %bitcast_pointer_v4i32_v3i32 @bitcast_pointer_v4i32_v3i32.body(<3 x i32>* undef)
; REF-NEXT: %3 = extractvalue %bitcast_pointer_v4i32_v3i32 %2, 0
; REF-NEXT: store <3 x i32> %3, <3 x i32>* %0, align 16
; REF-NEXT: ret void
define internal void @bitcast_pointer_v4i32_v3i32(<3 x i32>* %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_v4i32_v3i32
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile <4 x i32>, ptr addrspace(1) undef, align 16
; CHECK-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x i32> [[LOAD]], ptr [[BITCAST]], align 16
; CHECK-NEXT:    ret void
;
  %load = load volatile <4 x i32>, <4 x i32> addrspace(1)* undef
  %bitcast = bitcast <3 x i32>* %out to <4 x i32>*
  store <4 x i32> %load, <4 x i32>* %bitcast
  ret void
}

define void @bitcast_pointer_v4i32_v3i32_caller(<3 x i32>* %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_v4i32_v3i32_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_pointer_v4i32_v3i32(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_pointer_v4i32_v3i32(<3 x i32>* %out)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_pointer_v4i32_v3f32 @bitcast_pointer_v4i32_v3f32.body(<3 x float>* %out) #0 {
; REF-NEXT: %load = load volatile <4 x i32>, <4 x i32> addrspace(1)* undef
; REF-NEXT: %bitcast = bitcast <3 x float>* %out to <4 x i32>*
; REF-NEXT: %1 = shufflevector <4 x i32> %load, <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
; REF-NEXT: %2 = bitcast <3 x i32> %1 to <3 x float>
; REF-NEXT: %3 = insertvalue %bitcast_pointer_v4i32_v3f32 undef, <3 x float> %2, 0
; REF-NEXT: ret %bitcast_pointer_v4i32_v3f32 %3
define internal void @bitcast_pointer_v4i32_v3f32(<3 x float>* %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_v4i32_v3f32
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile <4 x i32>, ptr addrspace(1) undef, align 16
; CHECK-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x i32> [[LOAD]], ptr [[BITCAST]], align 16
; CHECK-NEXT:    ret void
;
  %load = load volatile <4 x i32>, <4 x i32> addrspace(1)* undef
  %bitcast = bitcast <3 x float>* %out to <4 x i32>*
  store <4 x i32> %load, <4 x i32>* %bitcast
  ret void
}

define void @bitcast_pointer_v4i32_v3f32_caller(<3 x float>* %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_v4i32_v3f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_pointer_v4i32_v3f32(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_pointer_v4i32_v3f32(<3 x float>* %out)
  ret void
}

; *** TODO: bitcast support
; Try different element and bitwidths which could produce broken
; casts.

; REF-LABEL: define private %bitcast_pointer_i32_f32 @bitcast_pointer_i32_f32.body(float* %out) #0 {
; REF-NEXT: %load = load volatile i32, ptr addrspace(1) undef
; REF-NEXT: %bitcast = bitcast float* %out to i32*
; REF-NEXT: %1 = bitcast i32 %load to float
; REF-NEXT: %2 = insertvalue %bitcast_pointer_i32_f32 undef, float %1, 0
; REF-NEXT: ret %bitcast_pointer_i32_f32 %2

; REF-LABEL: define internal void @bitcast_pointer_i32_f32(float* %0) #2 {
; REF-NEXT: %2 = call %bitcast_pointer_i32_f32 @bitcast_pointer_i32_f32.body(float* undef)
; REF-NEXT: %3 = extractvalue %bitcast_pointer_i32_f32 %2, 0
; REF-NEXT: store float %3, float* %0, align 4
define internal void @bitcast_pointer_i32_f32(float* %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_i32_f32
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store i32 [[LOAD]], ptr [[BITCAST]], align 4
; CHECK-NEXT:    ret void
;
  %load = load volatile i32, ptr addrspace(1) undef
  %bitcast = bitcast float* %out to i32*
  store i32 %load, ptr %bitcast
  ret void
}

define void @bitcast_pointer_i32_f32_caller(float* %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_i32_f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_pointer_i32_f32(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_pointer_i32_f32(float* %out)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_pointer_i32_f16(half* %out) #0 {
; REF-NOT: call
define internal void @bitcast_pointer_i32_f16(half* %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_i32_f16
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile i32, ptr addrspace(1) undef, align 4
; CHECK-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store i32 [[LOAD]], ptr [[BITCAST]], align 4
; CHECK-NEXT:    ret void
;
  %load = load volatile i32, ptr addrspace(1) undef
  %bitcast = bitcast half* %out to i32*
  store i32 %load, ptr %bitcast
  ret void
}

define void @bitcast_pointer_i32_f16_caller(half* %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_i32_f16_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_pointer_i32_f16(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_pointer_i32_f16(half* %out)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_pointer_f16_i32(ptr %out) #0 {
; REF-NOT: call
define internal void @bitcast_pointer_f16_i32(ptr %out) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_f16_i32
; CHECK-SAME: (ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LOAD:%.*]] = load volatile half, ptr addrspace(1) undef, align 2
; CHECK-NEXT:    [[BITCAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store half [[LOAD]], ptr [[BITCAST]], align 2
; CHECK-NEXT:    ret void
;
  %load = load volatile half, half addrspace(1)* undef
  %bitcast = bitcast ptr %out to half*
  store half %load, half* %bitcast
  ret void
}

define void @bitcast_pointer_f16_i32_caller(ptr %out) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_pointer_f16_i32_caller
; CHECK-SAME: (ptr [[OUT:%.*]]) {
; CHECK-NEXT:    call void @bitcast_pointer_f16_i32(ptr [[OUT]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_pointer_f16_i32(ptr %out)
  ret void
}

%struct.i128 = type { i128 }
%struct.v2f32 = type { <2 x float> }
%struct.v3f32 = type { <3 x float> }
%struct.v3f32.f32 = type { <3 x float>, float }
%struct.v4f32 = type { <4 x float> }

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_v3f32_v3f32 @bitcast_struct_v3f32_v3f32.body(%struct.v3f32* %out, <3 x float> %value) #0 {
; REF-NEXT: %extractVec = shufflevector <3 x float> %value, <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
; REF-NEXT: %cast = bitcast %struct.v3f32* %out to <4 x float>*
; REF-NEXT: %1 = shufflevector <4 x float> %extractVec, <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
; REF-NEXT: %2 = insertvalue %struct.v3f32 undef, <3 x float> %1, 0
; REF-NEXT: %3 = insertvalue %bitcast_struct_v3f32_v3f32 undef, %struct.v3f32 %2, 0
; REF-NEXT: ret %bitcast_struct_v3f32_v3f32 %3

; REF-LABEL: define internal void @bitcast_struct_v3f32_v3f32(%struct.v3f32* %0, <3 x float> %1) #2 {
; REF-NEXT: %3 = call %bitcast_struct_v3f32_v3f32 @bitcast_struct_v3f32_v3f32.body(%struct.v3f32* undef, <3 x float> %1)
; REF-NEXT: %4 = extractvalue %bitcast_struct_v3f32_v3f32 %3, 0
; REF-NEXT: store %struct.v3f32 %4, %struct.v3f32* %0, align 16
; REF-NEXT: ret void
define internal void @bitcast_struct_v3f32_v3f32(%struct.v3f32* %out, <3 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v3f32
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[VALUE]], <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %extractVec = shufflevector <3 x float> %value, <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
  %cast = bitcast %struct.v3f32* %out to <4 x float>*
  store <4 x float> %extractVec, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_v3f32_v3f32_caller(%struct.v3f32* %out, <3 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v3f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_v3f32(ptr [[OUT]], <3 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_v3f32(%struct.v3f32* %out, <3 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_v3f32_v3i32 @bitcast_struct_v3f32_v3i32.body(%struct.v3f32* %out, <3 x i32> %value) #0 {
; REF-NEXT: %extractVec = shufflevector <3 x i32> %value, <3 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
; REF-NEXT: %cast = bitcast %struct.v3f32* %out to <4 x i32>*
; REF-NEXT: %1 = shufflevector <4 x i32> %extractVec, <4 x i32> poison, <3 x i32> <i32 0, i32 1, i32 2>
; REF-NEXT: %2 = bitcast <3 x i32> %1 to <3 x float>
; REF-NEXT: %3 = insertvalue %struct.v3f32 undef, <3 x float> %2, 0
; REF-NEXT: %4 = insertvalue %bitcast_struct_v3f32_v3i32 undef, %struct.v3f32 %3, 0
; REF-NEXT: ret %bitcast_struct_v3f32_v3i32 %4

; REF-LABEL: define internal void @bitcast_struct_v3f32_v3i32(%struct.v3f32* %0, <3 x i32> %1) #2 {
; REF-NEXT: %3 = call %bitcast_struct_v3f32_v3i32 @bitcast_struct_v3f32_v3i32.body(%struct.v3f32* undef, <3 x i32> %1)
; REF-NEXT: %4 = extractvalue %bitcast_struct_v3f32_v3i32 %3, 0
; REF-NEXT: store %struct.v3f32 %4, %struct.v3f32* %0, align 16
define internal void @bitcast_struct_v3f32_v3i32(%struct.v3f32* %out, <3 x i32> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v3i32
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x i32> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x i32> [[VALUE]], <3 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x i32> [[EXTRACTVEC]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %extractVec = shufflevector <3 x i32> %value, <3 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
  %cast = bitcast %struct.v3f32* %out to <4 x i32>*
  store <4 x i32> %extractVec, <4 x i32>* %cast, align 16
  ret void
}

define void @bitcast_struct_v3f32_v3i32_caller(%struct.v3f32* %out, <3 x i32> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v3i32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x i32> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_v3i32(ptr [[OUT]], <3 x i32> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_v3i32(%struct.v3f32* %out, <3 x i32> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_v4f32_v4f32 @bitcast_struct_v4f32_v4f32.body(%struct.v4f32* %out, <4 x float> %value) #0 {
; REF-NEXT: %cast = bitcast %struct.v4f32* %out to <4 x float>*
; REF-NEXT: %1 = insertvalue %struct.v4f32 undef, <4 x float> %value, 0
; REF-NEXT: %2 = insertvalue %bitcast_struct_v4f32_v4f32 undef, %struct.v4f32 %1, 0
; REF-NEXT: ret %bitcast_struct_v4f32_v4f32 %2

; REF-LABEL: define internal void @bitcast_struct_v4f32_v4f32(%struct.v4f32* %0, <4 x float> %1) #2 {
; REF-NEXT: %3 = call %bitcast_struct_v4f32_v4f32 @bitcast_struct_v4f32_v4f32.body(%struct.v4f32* undef, <4 x float> %1)
define internal void @bitcast_struct_v4f32_v4f32(%struct.v4f32* %out, <4 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v4f32_v4f32
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[VALUE]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %cast = bitcast %struct.v4f32* %out to <4 x float>*
  store <4 x float> %value, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_v4f32_v4f32_caller(%struct.v4f32* %out, <4 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v4f32_v4f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v4f32_v4f32(ptr [[OUT]], <4 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v4f32_v4f32(%struct.v4f32* %out, <4 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_v3f32_v4i32 @bitcast_struct_v3f32_v4i32.body(%struct.v3f32* %out, <4 x i32> %value) #0 {
; REF-LABEL: define internal void @bitcast_struct_v3f32_v4i32(%struct.v3f32* %0, <4 x i32> %1) #2 {
define internal void @bitcast_struct_v3f32_v4i32(%struct.v3f32* %out, <4 x i32> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v4i32
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x i32> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x i32> [[VALUE]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %cast = bitcast %struct.v3f32* %out to <4 x i32>*
  store <4 x i32> %value, <4 x i32>* %cast, align 16
  ret void
}

define void @bitcast_struct_v3f32_v4i32_caller(%struct.v3f32* %out, <4 x i32> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v4i32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x i32> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_v4i32(ptr [[OUT]], <4 x i32> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_v4i32(%struct.v3f32* %out, <4 x i32> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_v4f32_v3f32 @bitcast_struct_v4f32_v3f32.body(%struct.v4f32* %out, <3 x float> %value) #0 {
; REF-LABEL: define internal void @bitcast_struct_v4f32_v3f32(%struct.v4f32* %0, <3 x float> %1) #2 {
define internal void @bitcast_struct_v4f32_v3f32(%struct.v4f32* %out, <3 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v4f32_v3f32
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[VALUE]], <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %extractVec = shufflevector <3 x float> %value, <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
  %cast = bitcast %struct.v4f32* %out to <4 x float>*
  store <4 x float> %extractVec, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_v4f32_v3f32_caller(%struct.v4f32* %out, <3 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v4f32_v3f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v4f32_v3f32(ptr [[OUT]], <3 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v4f32_v3f32(%struct.v4f32* %out, <3 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_struct_v3f32_v2f32(%struct.v3f32* %out, <2 x float> %value) #0 {
; REF-NOT: call
define internal void @bitcast_struct_v3f32_v2f32(%struct.v3f32* %out, <2 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v2f32
; CHECK-SAME: (ptr [[OUT:%.*]], <2 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <2 x float> [[VALUE]], ptr [[CAST]], align 8
; CHECK-NEXT:    ret void
;
  %cast = bitcast %struct.v3f32* %out to <2 x float>*
  store <2 x float> %value, <2 x float>* %cast, align 8
  ret void
}

define void @bitcast_struct_v3f32_v2f32_caller(%struct.v3f32* %out, <2 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_v2f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <2 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_v2f32(ptr [[OUT]], <2 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_v2f32(%struct.v3f32* %out, <2 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_struct_v3f32_f32_v3f32(%struct.v3f32.f32* %out, <3 x float> %value) #0 {
; REF-NOT: call
define internal void @bitcast_struct_v3f32_f32_v3f32(%struct.v3f32.f32* %out, <3 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_f32_v3f32
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[VALUE]], <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %extractVec = shufflevector <3 x float> %value, <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
  %cast = bitcast %struct.v3f32.f32* %out to <4 x float>*
  store <4 x float> %extractVec, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_v3f32_f32_v3f32_caller(%struct.v3f32.f32* %out, <3 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_f32_v3f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_f32_v3f32(ptr [[OUT]], <3 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_f32_v3f32(%struct.v3f32.f32* %out, <3 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_struct_v3f32_f32_v4f32(%struct.v3f32.f32* %out, <4 x float> %value) #0 {
; REF-NOT: call
define internal void @bitcast_struct_v3f32_f32_v4f32(%struct.v3f32.f32* %out, <4 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_f32_v4f32
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[VALUE]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %cast = bitcast %struct.v3f32.f32* %out to <4 x float>*
  store <4 x float> %value, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_v3f32_f32_v4f32_caller(%struct.v3f32.f32* %out, <4 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_v3f32_f32_v4f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_v3f32_f32_v4f32(ptr [[OUT]], <4 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_v3f32_f32_v4f32(%struct.v3f32.f32* %out, <4 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %bitcast_struct_i128_v4f32 @bitcast_struct_i128_v4f32.body(%struct.i128* %out, <4 x float> %value) #0 {
; REF-NEXT: %cast = bitcast %struct.i128* %out to <4 x float>*
; REF-NEXT: %1 = bitcast <4 x float> %value to i128
; REF-NEXT: %2 = insertvalue %struct.i128 undef, i128 %1, 0
; REF-NEXT: %3 = insertvalue %bitcast_struct_i128_v4f32 undef, %struct.i128 %2, 0
; REF-NEXT: ret %bitcast_struct_i128_v4f32 %3
define internal void @bitcast_struct_i128_v4f32(%struct.i128* %out, <4 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_i128_v4f32
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[VALUE]], ptr [[CAST]], align 16
; CHECK-NEXT:    ret void
;
  %cast = bitcast %struct.i128* %out to <4 x float>*
  store <4 x float> %value, <4 x float>* %cast, align 16
  ret void
}

define void @bitcast_struct_i128_v4f32_caller(%struct.i128* %out, <4 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_struct_i128_v4f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], <4 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_struct_i128_v4f32(ptr [[OUT]], <4 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_struct_i128_v4f32(%struct.i128* %out, <4 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_struct_i128_v4f32(%struct.i128* %0, <4 x float> %1) #2 {
; REF-NEXT: %3 = call %bitcast_struct_i128_v4f32 @bitcast_struct_i128_v4f32.body(%struct.i128* undef, <4 x float> %1)
define internal void @bitcast_array_v4i32_v4f32([4 x i32]* %out, [4 x float] %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_array_v4i32_v4f32
; CHECK-SAME: (ptr [[OUT:%.*]], [4 x float] [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store [4 x float] [[VALUE]], ptr [[CAST]], align 4
; CHECK-NEXT:    ret void
;
  %cast = bitcast [4 x i32]* %out to [4 x float]*
  store [4 x float] %value, [4 x float]* %cast, align 4
  ret void
}

define void @bitcast_array_v4i32_v4f32_caller([4 x i32]* %out, [4 x float] %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_array_v4i32_v4f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], [4 x float] [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_array_v4i32_v4f32(ptr [[OUT]], [4 x float] [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_array_v4i32_v4f32([4 x i32]* %out, [4 x float] %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define private %multi_return_bitcast_struct_v3f32_v3f32 @multi_return_bitcast_struct_v3f32_v3f32.body(i1 %cond, %struct.v3f32* %out, <3 x float> %value) #0 {
; REF: ret0:
; REF: %cast0 = bitcast %struct.v3f32* %out to <4 x float>*
; REF: %0 = shufflevector <4 x float> %extractVec, <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
; REF: %1 = insertvalue %struct.v3f32 undef, <3 x float> %0, 0
; REF: %2 = insertvalue %multi_return_bitcast_struct_v3f32_v3f32 undef, %struct.v3f32 %1, 0
; REF: ret %multi_return_bitcast_struct_v3f32_v3f32 %2

; REF: ret1:
; REF: %4 = insertvalue %struct.v3f32 undef, <3 x float> %3, 0
; REF: %5 = insertvalue %multi_return_bitcast_struct_v3f32_v3f32 undef, %struct.v3f32 %4, 0
; REF: ret %multi_return_bitcast_struct_v3f32_v3f32 %5
define internal void @multi_return_bitcast_struct_v3f32_v3f32(i1 %cond, %struct.v3f32* %out, <3 x float> %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@multi_return_bitcast_struct_v3f32_v3f32
; CHECK-SAME: (i1 [[COND:%.*]], ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[COND]], label [[RET0:%.*]], label [[RET1:%.*]]
; CHECK:       ret0:
; CHECK-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[VALUE]], <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 poison>
; CHECK-NEXT:    [[CAST0:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[CAST0]], align 16
; CHECK-NEXT:    ret void
; CHECK:       ret1:
; CHECK-NEXT:    [[CAST1:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    [[LOAD:%.*]] = load <4 x float>, ptr addrspace(1) undef, align 16
; CHECK-NEXT:    store <4 x float> [[LOAD]], ptr [[CAST1]], align 16
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cond, label %ret0, label %ret1

ret0:
  %extractVec = shufflevector <3 x float> %value, <3 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 undef>
  %cast0 = bitcast %struct.v3f32* %out to <4 x float>*
  store <4 x float> %extractVec, <4 x float>* %cast0, align 16
  ret void

ret1:
  %cast1 = bitcast %struct.v3f32* %out to <4 x float>*
  %load = load <4 x float>, <4 x float> addrspace(1)* undef
  store <4 x float> %load, <4 x float>* %cast1, align 16
  ret void
}

define void @multi_return_bitcast_struct_v3f32_v3f32_caller(i1 %cond, %struct.v3f32* %out, <3 x float> %value) {
; CHECK-LABEL: define {{[^@]+}}@multi_return_bitcast_struct_v3f32_v3f32_caller
; CHECK-SAME: (i1 [[COND:%.*]], ptr [[OUT:%.*]], <3 x float> [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @multi_return_bitcast_struct_v3f32_v3f32(i1 [[COND]], ptr [[OUT]], <3 x float> [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @multi_return_bitcast_struct_v3f32_v3f32(i1 %cond, %struct.v3f32* %out, <3 x float> %value)
  ret void
}

; *** TODO: bitcast support
; REF-LABEL: define internal void @bitcast_v3f32_struct_v3f32(<3 x float>* %out, %struct.v3f32 %value) #0 {
; REF-NOT: call
define internal void @bitcast_v3f32_struct_v3f32(<3 x float>* %out, %struct.v3f32 %value) #0 {
; CHECK-LABEL: define {{[^@]+}}@bitcast_v3f32_struct_v3f32
; CHECK-SAME: (ptr [[OUT:%.*]], [[STRUCT_V3F32:%.*]] [[VALUE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr [[OUT]] to ptr
; CHECK-NEXT:    store [[STRUCT_V3F32]] [[VALUE]], ptr [[CAST]], align 4
; CHECK-NEXT:    ret void
;
  %cast = bitcast <3 x float>* %out to %struct.v3f32*
  store %struct.v3f32 %value, %struct.v3f32* %cast, align 4
  ret void
}

define void @bitcast_v3f32_struct_v3f32_caller(<3 x float>* %out, %struct.v3f32 %value) {
; CHECK-LABEL: define {{[^@]+}}@bitcast_v3f32_struct_v3f32_caller
; CHECK-SAME: (ptr [[OUT:%.*]], [[STRUCT_V3F32:%.*]] [[VALUE:%.*]]) {
; CHECK-NEXT:    call void @bitcast_v3f32_struct_v3f32(ptr [[OUT]], [[STRUCT_V3F32]] [[VALUE]])
; CHECK-NEXT:    ret void
;
  call void @bitcast_v3f32_struct_v3f32(<3 x float>* %out, %struct.v3f32 %value)
  ret void
}

attributes #0 = { nounwind }
attributes #1 = { nounwind noinline optnone }
attributes #2 = { alwaysinline nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "clang version 5.0.0", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !2)
!1 = !DIFile(filename: "code-object-metadata-kernel-debug-props.cl", directory: "/some/random/directory")
!2 = !{}
!3 = !{i32 2, !"Dwarf Version", i32 2}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = distinct !DISubprogram(name: "test", scope: !1, file: !1, line: 1, type: !6, isLocal: false, isDefinition: true, scopeLine: 1, flags: DIFlagPrototyped, isOptimized: false, unit: !0, retainedNodes: !2)
!6 = !DISubroutineType(types: !7)
!7 = !{null, !8}
!8 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !9, size: 64)
!9 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!10 = !DILocation(line: 2, column: 3, scope: !5)
!11 = !DILocation(line: 2, column: 8, scope: !5)
!12 = !DILocation(line: 3, column: 3, scope: !5)
!13 = !{!"none"}
