# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O0 -amdgpu-late-wave-transform=1 -run-pass=amdgpu-pre-wave-transform -verify-machineinstrs %s -o - | FileCheck -check-prefix=CHECK %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O3 -amdgpu-late-wave-transform=1 -run-pass=amdgpu-pre-wave-transform -verify-machineinstrs %s -o - | FileCheck -check-prefix=CHECK %s

# Test that AMDGPUPreWaveTransform drops a redundant SI_BRCOND when both arms
# target the same block. This mirrors what StructurizeCFG does in the non-LWT
# pipeline when a switch leaf compares against a value but both successors
# converge on the unified return / flow block. The dead V_CMP defining the
# condition is removed when it has no remaining uses.

# Case 1: SI_BRCOND target equals the subsequent S_BRANCH target. Both the
# SI_BRCOND and its (now dead) V_CMP must be removed.
---
name: redundant_brcond_explicit_branch
body: |
  ; CHECK-LABEL: name: redundant_brcond_explicit_branch
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CHECK-NEXT:   S_BRANCH %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $vgpr0

    %0:vgpr_32 = COPY $vgpr0
    %1:sreg_64 = V_CMP_EQ_U32_e64 0, %0, implicit $exec
    SI_BRCOND %bb.1, killed %1
    S_BRANCH %bb.1

  bb.1:
    S_ENDPGM 0
...

# Case 2: SI_BRCOND target equals the layout-next fallthrough block; no
# explicit S_BRANCH is present. Both the SI_BRCOND and its dead V_CMP must
# be removed.
---
name: redundant_brcond_fallthrough
body: |
  ; CHECK-LABEL: name: redundant_brcond_fallthrough
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $vgpr0

    %0:vgpr_32 = COPY $vgpr0
    %1:sreg_64 = V_CMP_EQ_U32_e64 0, %0, implicit $exec
    SI_BRCOND %bb.1, killed %1

  bb.1:
    S_ENDPGM 0
...

# Case 3: Redundant SI_BRCOND, but the V_CMP result is also consumed by
# another instruction. The SI_BRCOND must still be removed; the V_CMP must
# be preserved.
---
name: redundant_brcond_vcmp_has_other_use
body: |
  ; CHECK-LABEL: name: redundant_brcond_vcmp_has_other_use
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CHECK-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 0, [[COPY]], implicit $exec
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sreg_64 = COPY [[V_CMP_EQ_U32_e64_]]
  ; CHECK-NEXT:   S_BRANCH %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $vgpr0

    %0:vgpr_32 = COPY $vgpr0
    %1:sreg_64 = V_CMP_EQ_U32_e64 0, %0, implicit $exec
    %2:sreg_64 = COPY %1
    SI_BRCOND %bb.1, %1
    S_BRANCH %bb.1

  bb.1:
    S_ENDPGM 0
...
