# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O0 -amdgpu-late-wave-transform=1 -run-pass=amdgpu-pre-wave-transform -verify-machineinstrs %s -o - | FileCheck -check-prefix=CHECK %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O3 -amdgpu-late-wave-transform=1 -run-pass=amdgpu-pre-wave-transform -verify-machineinstrs %s -o - | FileCheck -check-prefix=CHECK %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O0 -amdgpu-late-wave-transform=1 -passes=amdgpu-pre-wave-transform %s -o - | FileCheck -check-prefix=CHECK %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O3 -amdgpu-late-wave-transform=1 -passes=amdgpu-pre-wave-transform %s -o - | FileCheck -check-prefix=CHECK %s

# Test that AMDGPUPreWaveTransform prepares the machine function for wave transform.

---
name: test_waterfall_loop_opcode_transition
body: |
  ; CHECK-LABEL: name: test_waterfall_loop_opcode_transition
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.0(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $vgpr1 = V_ADD_U32_e32 $vgpr0, $vgpr0, implicit $exec
  ; CHECK-NEXT:   S_CBRANCH_EXECNZ %bb.0, implicit $exec
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    liveins: $vgpr0

    $vgpr1 = V_ADD_U32_e32 $vgpr0, $vgpr0, implicit $exec
    SI_WATERFALL_LOOP %bb.0, implicit $exec

  bb.1:
    S_ENDPGM 0
...
