; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -O0 -amdgpu-late-wave-transform=1 \
; RUN:   -stop-after=amdgpu-finalize-isel-wave-transform -verify-machineinstrs %s -o - | FileCheck %s

; Test that late-wave finalize preserves `vreg_1` webs that feed `$scc` and
; lowers the final SCC copy after reclassing the source web to lane-mask SGPRs.
; In late-wave mode, SI Fix SGPR Copies leaves the SCC copy in place. Finalize
; keeps that source in lane-mask form and then sets SCC with `S_AND_B64`.

%asm.output = type { <16 x i32>, <16 x i32>, <16 x i32>, <8 x i32>,
                     <2 x i32>, i32,
                     <16 x i32>, <7 x i32>,
                     i64 }

define void @scc_from_vreg1_lanemask() #0 {
  ; CHECK-LABEL: name: scc_from_vreg1_lanemask
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 %stack.0.alloca0
  ; CHECK-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 killed [[S_MOV_B32_]]
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_1]]
  ; CHECK-NEXT:   INLINEASM &"; use alloca0 $0", 1 /* sideeffect attdialect */, 1114121 /* reguse:VGPR_32 */, [[COPY]]
  ; CHECK-NEXT:   INLINEASM &"; def $0, $1, $2, $3, $4, $5, $6, $7, $8", 1 /* sideeffect attdialect */, 10 /* regdef */, implicit-def $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15, 10 /* regdef */, implicit-def $sgpr16_sgpr17_sgpr18_sgpr19_sgpr20_sgpr21_sgpr22_sgpr23_sgpr24_sgpr25_sgpr26_sgpr27_sgpr28_sgpr29_sgpr30_sgpr31, 10 /* regdef */, implicit-def $sgpr32_sgpr33_sgpr34_sgpr35_sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47, 10 /* regdef */, implicit-def $sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55, 10 /* regdef */, implicit-def $sgpr56_sgpr57, 10 /* regdef */, implicit-def $sgpr58, 10 /* regdef */, implicit-def $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 10 /* regdef */, implicit-def $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22, 10 /* regdef */, implicit-def $vcc
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sgpr_512 = COPY $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:sgpr_512 = COPY $sgpr16_sgpr17_sgpr18_sgpr19_sgpr20_sgpr21_sgpr22_sgpr23_sgpr24_sgpr25_sgpr26_sgpr27_sgpr28_sgpr29_sgpr30_sgpr31
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:sgpr_512 = COPY $sgpr32_sgpr33_sgpr34_sgpr35_sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:sgpr_256 = COPY $sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:sreg_64 = COPY $sgpr56_sgpr57
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:sreg_32 = COPY $sgpr58
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:vreg_512 = COPY $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:vreg_224 = COPY $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22
  ; CHECK-NEXT:   [[COPY9:%[0-9]+]]:sreg_64 = COPY $vcc
  ; CHECK-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 %stack.1.alloca1
  ; CHECK-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 killed [[S_MOV_B32_2]]
  ; CHECK-NEXT:   [[S_MOV_B64_:%[0-9]+]]:sreg_64 = S_MOV_B64 0
  ; CHECK-NEXT:   $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15 = COPY [[COPY1]]
  ; CHECK-NEXT:   $sgpr16_sgpr17_sgpr18_sgpr19_sgpr20_sgpr21_sgpr22_sgpr23_sgpr24_sgpr25_sgpr26_sgpr27_sgpr28_sgpr29_sgpr30_sgpr31 = COPY [[COPY2]]
  ; CHECK-NEXT:   $sgpr32_sgpr33_sgpr34_sgpr35_sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47 = COPY [[COPY3]]
  ; CHECK-NEXT:   $sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55 = COPY [[COPY4]]
  ; CHECK-NEXT:   $sgpr56_sgpr57 = COPY [[COPY5]]
  ; CHECK-NEXT:   $sgpr58 = COPY [[COPY6]]
  ; CHECK-NEXT:   $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15 = COPY [[COPY7]]
  ; CHECK-NEXT:   $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22 = COPY [[COPY8]]
  ; CHECK-NEXT:   $vcc = COPY [[COPY9]]
  ; CHECK-NEXT:   $sgpr54 = COPY [[S_MOV_B32_3]]
  ; CHECK-NEXT:   [[COPY10:%[0-9]+]]:sreg_64 = COPY [[S_MOV_B64_]]
  ; CHECK-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[COPY10]], $exec, implicit-def $scc
  ; CHECK-NEXT:   INLINEASM &"; use $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10", 1 /* sideeffect attdialect */, 9 /* reguse */, $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11_sgpr12_sgpr13_sgpr14_sgpr15, 9 /* reguse */, $sgpr16_sgpr17_sgpr18_sgpr19_sgpr20_sgpr21_sgpr22_sgpr23_sgpr24_sgpr25_sgpr26_sgpr27_sgpr28_sgpr29_sgpr30_sgpr31, 9 /* reguse */, $sgpr32_sgpr33_sgpr34_sgpr35_sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47, 9 /* reguse */, $sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55, 9 /* reguse */, $sgpr56_sgpr57, 9 /* reguse */, $sgpr58, 9 /* reguse */, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, 9 /* reguse */, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22, 9 /* reguse */, $vcc, 9 /* reguse */, $sgpr54, 9 /* reguse */, $scc
  ; CHECK-NEXT:   SI_RETURN
  %alloca0 = alloca [4096 x i32], align 64, addrspace(5)
  %alloca1 = alloca i32, align 4, addrspace(5)
  call void asm sideeffect "; use alloca0 $0", "v"(ptr addrspace(5) %alloca0)
  %asm = call %asm.output asm sideeffect "; def $0, $1, $2, $3, $4, $5, $6, $7, $8", "={s[0:15]},={s[16:31]},={s[32:47]},={s[48:55]},={s[56:57]},={s58},={v[0:15]},={v[16:22]},={vcc}"()
  %s0 = extractvalue %asm.output %asm, 0
  %s1 = extractvalue %asm.output %asm, 1
  %s2 = extractvalue %asm.output %asm, 2
  %s3 = extractvalue %asm.output %asm, 3
  %s4 = extractvalue %asm.output %asm, 4
  %s5 = extractvalue %asm.output %asm, 5
  %v0 = extractvalue %asm.output %asm, 6
  %v1 = extractvalue %asm.output %asm, 7
  %vcc = extractvalue %asm.output %asm, 8
  call void asm sideeffect "; use $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10", "{s[0:15]},{s[16:31]},{s[32:47]},{s[48:55]},{s[56:57]},{s58},{v[0:15]},{v[16:22]},{vcc},{s54},{scc}"(<16 x i32> %s0, <16 x i32> %s1, <16 x i32> %s2, <8 x i32> %s3, <2 x i32> %s4, i32 %s5, <16 x i32> %v0, <7 x i32> %v1, i64 %vcc, ptr addrspace(5) %alloca1, i32 0)
  ret void
}

attributes #0 = { nounwind "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" }
