# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 \
# RUN:   -amdgpu-late-wave-transform=1 \
# RUN:   -run-pass=si-fix-sgpr-copies,amdgpu-finalize-isel-wave-transform \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

# Test late-wave vreg_1 lowering in AMDGPUFinalizeISelWaveTransform.
#
# In late-wave mode, `SIFixSGPRCopies` leaves `$scc = COPY %vreg_1` untouched.
# The finalize pass preserves source webs that feed physical-register copies,
# then lowers the SCC copy at the boundary:
#   vreg_1 -> vgpr_32 via V_CNDMASK_B32_e64
#   vgpr_32 -> wave mask via V_CMP_NE_U32_e64
#   wave mask -> $scc via S_AND_B64/S_AND_B32 with EXEC

# Copy chain feeding SCC: the transport web stays in lane-mask form, and the
# final SCC copy lowers to S_AND_B64 once the web has been reclassed.
---
name:              preserve_vreg1_copy_chain
machineFunctionInfo:
  isWaveCFG: false
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: preserve_vreg1_copy_chain
    ; CHECK: [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY0:%[0-9]+]]:sreg_64 = COPY [[DEF]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:sreg_64 = COPY [[COPY0]]
    ; CHECK-NEXT: [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[COPY1]], $exec, implicit-def $scc
    ; CHECK-NEXT: [[S_CSELECT_B64_:%[0-9]+]]:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
    ; CHECK-NEXT: S_ENDPGM 0
    %0:sreg_64 = IMPLICIT_DEF
    %1:vreg_1 = COPY %0
    %2:vreg_1 = COPY %1
    $scc = COPY %2
    %3:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
    S_ENDPGM 0
...

# PHI chain feeding SCC: the entire transport web stays in lane-mask form and
# the SCC copy is lowered locally in the destination block.
---
name:              preserve_vreg1_phi_chain
machineFunctionInfo:
  isWaveCFG: false
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: preserve_vreg1_phi_chain
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:sreg_64 = COPY [[DEF]]
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sreg_64 = COPY [[DEF1]]
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:sreg_64 = PHI [[COPY]], %bb.0, [[COPY1]], %bb.1
  ; CHECK-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[PHI]], $exec, implicit-def $scc
  ; CHECK-NEXT:   [[S_CSELECT_B64_:%[0-9]+]]:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    %0:sreg_64 = IMPLICIT_DEF
    %1:vreg_1 = COPY %0
    S_BRANCH %bb.2

  bb.1:
    %2:sreg_64 = IMPLICIT_DEF
    %3:vreg_1 = COPY %2
    S_BRANCH %bb.2

  bb.2:
    %4:vreg_1 = PHI %1, %bb.0, %3, %bb.1
    $scc = COPY %4
    %5:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
    S_ENDPGM 0
...

# Boundary case: vreg_1 from a lane mask with only VGPR consumers.
# Must widen to VGPR_32 via V_CNDMASK_B32_e64 (no scalar consumer).
---
name:              widen_vreg1_no_scalar_consumer
machineFunctionInfo:
  isWaveCFG: false
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: widen_vreg1_no_scalar_consumer
    ; CHECK: [[DEF:%[0-9]+]]:sreg_64_xexec = IMPLICIT_DEF
    ; CHECK-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[DEF]], implicit $exec
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[V_CNDMASK_B32_e64_]]
    ; CHECK-NEXT: S_ENDPGM 0
    %0:sreg_64 = IMPLICIT_DEF
    %1:vreg_1 = COPY %0
    %2:vgpr_32 = COPY %1
    S_ENDPGM 0
...

# Deferred SCC + VGPR users across blocks: the SCC-feeding source stays a lane
# mask while the separate VGPR user still widens at its own boundary.
---
name:              preserve_vreg1_deferred_cross_block
machineFunctionInfo:
  isWaveCFG: false
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: preserve_vreg1_deferred_cross_block
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   [[WIDE:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[COPY:%[0-9]+]], implicit $exec
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY [[WIDE]]
  ; CHECK-NEXT:   S_ENDPGM 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:sreg_64_xexec = COPY [[DEF]]
  ; CHECK-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[COPY]], $exec, implicit-def $scc
  ; CHECK-NEXT:   [[S_CSELECT_B64_:%[0-9]+]]:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
  ; CHECK-NEXT:   S_BRANCH %bb.1
  bb.0:
    S_BRANCH %bb.2

  bb.1:
    %2:vreg_1 = COPY %1
    %3:vgpr_32 = COPY %2
    S_ENDPGM 0

  bb.2:
    %0:sreg_64 = IMPLICIT_DEF
    %1:vreg_1 = COPY %0
    $scc = COPY %1
    %4:sreg_64 = S_CSELECT_B64 -1, 0, implicit $scc
    S_BRANCH %bb.1
...
