; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=1 -amdgpu-late-wave-transform=1 -O0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 -verify-machineinstrs -stop-after=amdgpu-global-isel-divergence-lowering < %s | FileCheck %s

; AMDGPUGlobalISelDivergenceLowering folds a uniform G_PHI that merges a single
; real value through divergent control flow. Only observable at -O0.

; A uniform phi whose incomings are the same kernel-arg value on both edges of a
; divergent branch folds to that value: no G_PHI survives.
define amdgpu_kernel void @uniform_phi_single_value(i32 %n, ptr addrspace(1) %out) {
  ; CHECK-LABEL: name: uniform_phi_single_value
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $sgpr8_sgpr9, $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr8_sgpr9
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32(i32) = COPY $vgpr0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[COPY]](p4) :: (invariant load (i32) from %ir.n.kernarg.offset, align 16, addrspace 4)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = nuw nusw inbounds G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(p1) = G_LOAD [[PTR_ADD]](p4) :: (invariant load (p1) from %ir.out.kernarg.offset, addrspace 4)
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(i32) = G_ASSERT_ZEXT [[COPY1]], 10
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:sreg_32_xm0_xexec(i1) = G_ICMP intpred(sge), [[ASSERT_ZEXT]](i32), [[LOAD]]
  ; CHECK-NEXT:   SI_BRCOND %bb.3, [[ICMP]](i1), implicit-def $exec, implicit-def $vcc, implicit $exec
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.end:
  ; CHECK-NEXT:   G_STORE [[LOAD]](i32), [[LOAD1]](p1) :: (store (i32) into %ir.out.load, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %cmp = icmp slt i32 %tid, %n
  br i1 %cmp, label %if, label %end

if:
  br label %end

end:
  %phi = phi i32 [ %n, %entry ], [ %n, %if ]
  store i32 %phi, ptr addrspace(1) %out
  ret void
}

; A uniform phi merging a dominating uniform value with an undef (G_IMPLICIT_DEF)
; incoming also folds to the dominating value.
define amdgpu_kernel void @uniform_phi_with_undef(i32 %n, ptr addrspace(1) %out) {
  ; CHECK-LABEL: name: uniform_phi_with_undef
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT:   liveins: $sgpr8_sgpr9, $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr8_sgpr9
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32(i32) = COPY $vgpr0
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(i32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[COPY]](p4) :: (invariant load (i32) from %ir.n.kernarg.offset, align 16, addrspace 4)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = nuw nusw inbounds G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(p1) = G_LOAD [[PTR_ADD]](p4) :: (invariant load (p1) from %ir.out.kernarg.offset, addrspace 4)
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(i32) = G_ASSERT_ZEXT [[COPY1]], 10
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:sreg_32_xm0_xexec(i1) = G_ICMP intpred(sge), [[ASSERT_ZEXT]](i32), [[LOAD]]
  ; CHECK-NEXT:   SI_BRCOND %bb.3, [[ICMP]](i1), implicit-def $exec, implicit-def $vcc, implicit $exec
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.end:
  ; CHECK-NEXT:   G_STORE [[LOAD]](i32), [[LOAD1]](p1) :: (store (i32) into %ir.out.load, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %cmp = icmp slt i32 %tid, %n
  br i1 %cmp, label %if, label %end

if:
  br label %end

end:
  %phi = phi i32 [ %n, %entry ], [ undef, %if ]
  store i32 %phi, ptr addrspace(1) %out
  ret void
}

; A divergent i1 phi is not simplified; it is widened to an s32 G_PHI and the s1
; value is rematerialized with a G_ICMP.
define amdgpu_kernel void @widen_divergent_i1_phi(i32 %n, ptr addrspace(1) %out) {
  ; CHECK-LABEL: name: widen_divergent_i1_phi
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $sgpr8_sgpr9, $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr8_sgpr9
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32(i32) = COPY $vgpr0
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[COPY]](p4) :: (invariant load (i32) from %ir.n.kernarg.offset, align 16, addrspace 4)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = nuw nusw inbounds G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(p1) = G_LOAD [[PTR_ADD]](p4) :: (invariant load (p1) from %ir.out.kernarg.offset, addrspace 4)
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(i32) = G_ASSERT_ZEXT [[COPY1]], 10
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(i1) = G_CONSTANT i1 false
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[C1]](i1), [[C2]], [[C3]]
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(i32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   G_BR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.loop:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:_(i32) = G_PHI [[C4]](i32), %bb.1, %25(i32), %bb.2
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:_(s32) = G_PHI [[SELECT]](s32), %bb.1, %39(s32), %bb.2
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[ICMP:%[0-9]+]]:_(i1) = G_ICMP intpred(ne), [[PHI1]](s32), [[C5]]
  ; CHECK-NEXT:   [[ICMP1:%[0-9]+]]:_(i1) = G_ICMP intpred(slt), [[PHI]](i32), [[ASSERT_ZEXT]]
  ; CHECK-NEXT:   [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 -1
  ; CHECK-NEXT:   [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
  ; CHECK-NEXT:   [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[ICMP1]](i1), [[C6]], [[C7]]
  ; CHECK-NEXT:   [[C8:%[0-9]+]]:_(i32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(i32) = G_ADD [[PHI]], [[C8]]
  ; CHECK-NEXT:   [[ICMP2:%[0-9]+]]:_(i1) = G_ICMP intpred(slt), [[ADD]](i32), [[LOAD]]
  ; CHECK-NEXT:   G_BRCOND [[ICMP2]](i1), %bb.2
  ; CHECK-NEXT:   G_BR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.end:
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[ICMP]](i1)
  ; CHECK-NEXT:   G_STORE [[ZEXT]](i32), [[LOAD1]](p1) :: (store (i32) into %ir.out.load, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
entry:
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %acc = phi i1 [ false, %entry ], [ %cond, %loop ]
  %cond = icmp slt i32 %iv, %tid
  %iv.next = add i32 %iv, 1
  %exit = icmp sge i32 %iv.next, %n
  br i1 %exit, label %end, label %loop

end:
  %ext = zext i1 %acc to i32
  store i32 %ext, ptr addrspace(1) %out
  ret void
}

declare i32 @llvm.amdgcn.workitem.id.x()
