# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -amdgpu-late-wave-transform=1 -mtriple=amdgcn -mcpu=gfx1010 -run-pass=amdgpu-wave-transform -verify-machineinstrs -o - %s 2>&1 | FileCheck -check-prefixes=POSTWT %s

# Test that an INLINEASM_BR block correctly participates as a contributing
# block in the lane mask framework.
#
# bb.1 is a contributing block when building lane masks for bb.3 and bb.2.
# Its active lanes must be correctly contributed via the accumulator.
# For INLINEASM_BR, the contribution is conservatively getAllOnes() since
# the branch condition is opaque to the compiler.
#
# CFG:
#
#       0 (divergent)
#      / \
#     1   \
# (uniform)|
#    / \   /
#   |   2<+
#   | (divergent)
#   |  / \
#   3<+   4
#    \   /
#      5
#
# - bb.0: divergent (SI_BRCOND) -> bb.1 (primary), bb.2 (secondary)
# - bb.1: uniform conditional (INLINEASM_BR) -> bb.2 (fallthrough), bb.3 (indirect target)
# - bb.2: divergent (SI_BRCOND) -> bb.3 (primary), bb.4 (secondary)
# - bb.3, bb.4: merge at bb.5

---
# The inline asm is opaque; exec is assumed invariant. bb.1 is a contributing
# block whose active lanes must be accumulated into the lane masks for its
# successors. Since the branch condition is opaque, the contribution is
# conservatively getAllOnes() (the user is responsible for inline asm
# correctness).
#
name: uniform_build_lane_mask_inlineasm
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: uniform_build_lane_mask_inlineasm
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_XOR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_MOV_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = S_OR_B32 [[V_CMP_EQ_U32_e64_]], [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_MOV_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_1]]
  ; POSTWT-NEXT:   INLINEASM_BR &"s_cbranch_vccnz ${0:l}", sideeffect attdialect, imm, %bb.8
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8 (inlineasm-br-indirect-target):
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[COPY2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[COPY2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_MOV_B32_4:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], [[S_MOV_B32_4]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_2]], [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_5]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.5, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.5(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $sgpr0

    %0:vgpr_32 = COPY $vgpr0
    %1:sreg_32 = COPY $sgpr0
    %2:sreg_32 = S_MOV_B32 0
    %3:sreg_32 = V_CMP_EQ_U32_e64 %0, %2, implicit $exec
    SI_BRCOND %bb.2, killed %3, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    INLINEASM_BR &"s_cbranch_vccnz ${0:l}", 1 /* sideeffect attdialect */, 13 /* imm */, %bb.3
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.3, %bb.4

    %4:sreg_32 = S_MOV_B32 1
    %5:sreg_32 = V_CMP_EQ_U32_e64 %0, %4, implicit $exec
    SI_BRCOND %bb.4, killed %5, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.3

  bb.3 (inlineasm-br-indirect-target):
    successors: %bb.5
    S_BRANCH %bb.5

  bb.4:
    successors: %bb.5
    S_BRANCH %bb.5

  bb.5:
    S_ENDPGM 0
...
