# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# REQUIRES: asserts
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 -verify-machineinstrs -amdgpu-late-wave-transform=1 -run-pass=amdgpu-wave-transform -o - %s | FileCheck -check-prefixes=POSTWT %s

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Divergent, 1: Divergent, 2:Divergent
---
name: partial_join_1
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_1
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = S_OR_B32 [[V_CMP_EQ_U32_e64_]], [[V_CMP_EQ_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_1]], [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_2]]
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_5]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $vgpr1, $vgpr2

    %1:vgpr_32 = COPY $vgpr0
    %2:vgpr_32 = COPY $vgpr1
    %3:vgpr_32 = COPY $vgpr2
    %4:sreg_32 = S_MOV_B32 0
    %5:sreg_32 = V_CMP_EQ_U32_e64 killed %1, %4, implicit $exec
    SI_BRCOND %bb.2, killed %5, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %6:sreg_32 = V_CMP_EQ_U32_e64 killed %2, %4, implicit $exec
    SI_BRCOND %bb.4, killed %6, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    %7:sreg_32 = V_CMP_EQ_U32_e64 killed %3, %4, implicit $exec
    SI_BRCOND %bb.5, killed %7, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Uniform, 1: Divergent, 2: Divergent
---
name: partial_join_2
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_2
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_XOR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_3]], [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_MOV_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $vgpr0, $vgpr1

    %1:sgpr_32 = COPY $sgpr0
    %2:vgpr_32 = COPY $vgpr0
    %3:vgpr_32 = COPY $vgpr1
    %4:sreg_32 = S_MOV_B32 0
    S_CMP_EQ_U32 killed %1, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit killed $scc
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %6:sreg_32 = V_CMP_EQ_U32_e64 killed %2, %4, implicit $exec
    SI_BRCOND %bb.4, killed %6, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    %7:sreg_32 = V_CMP_EQ_U32_e64 killed %3, %4, implicit $exec
    SI_BRCOND %bb.5, killed %7, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Divergent, 1: Uniform, 2: Divergent
---
name: partial_join_3
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_3
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.10(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY1]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.7, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.10:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_2]], [[S_XOR_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_MOV_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_]]
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $sgpr0, $vgpr1

    %1:vgpr_32 = COPY $vgpr0
    %2:sgpr_32 = COPY $sgpr0
    %3:vgpr_32 = COPY $vgpr1
    %4:sreg_32 = S_MOV_B32 0
    %5:sreg_32 = V_CMP_EQ_U32_e64 killed %1, %4, implicit $exec
    SI_BRCOND %bb.2, killed %5, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    S_CMP_EQ_U32 killed %2, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.4, implicit killed $scc
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    %7:sreg_32 = V_CMP_EQ_U32_e64 killed %3, %4, implicit $exec
    SI_BRCOND %bb.5, killed %7, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Divergent, 1: Divergent, 2: Uniform
---
name: partial_join_4
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_4
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = S_OR_B32 [[V_CMP_EQ_U32_e64_]], [[V_CMP_EQ_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY2]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_CSELECT_B32_:%[0-9]+]]:sreg_32 = S_CSELECT_B32 0, $exec_lo, implicit $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_1]], [[S_CSELECT_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_CSELECT_B32_1:%[0-9]+]]:sreg_32 = S_CSELECT_B32 $exec_lo, 0, implicit $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[S_CSELECT_B32_1]]
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $vgpr1, $sgpr0

    %1:vgpr_32 = COPY $vgpr0
    %2:vgpr_32 = COPY $vgpr1
    %3:sgpr_32 = COPY $sgpr0
    %4:sreg_32 = S_MOV_B32 0
    %5:sreg_32 = V_CMP_EQ_U32_e64 killed %1, %4, implicit $exec
    SI_BRCOND %bb.2, killed %5, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %6:sreg_32 = V_CMP_EQ_U32_e64 killed %2, %4, implicit $exec
    SI_BRCOND %bb.4, killed %6, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    S_CMP_EQ_U32 killed %3, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.5, implicit killed $scc
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Divergent, 1: Uniform, 2: Uniform
---
name: partial_join_5
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_5
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.10(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1, $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY1]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.7, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.10:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY2]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_CSELECT_B32_:%[0-9]+]]:sreg_32 = S_CSELECT_B32 0, $exec_lo, implicit $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_MOV_B32_2]], [[S_CSELECT_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_CSELECT_B32_1:%[0-9]+]]:sreg_32 = S_CSELECT_B32 $exec_lo, 0, implicit $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = COPY [[S_CSELECT_B32_1]]
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_MOV_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_]]
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $sgpr0, $sgpr1

    %1:vgpr_32 = COPY $vgpr0
    %2:sgpr_32 = COPY $sgpr0
    %3:sgpr_32 = COPY $sgpr1
    %4:sreg_32 = S_MOV_B32 0
    %5:sreg_32 = V_CMP_EQ_U32_e64 killed %1, %4, implicit $exec
    SI_BRCOND %bb.2, killed %5, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    S_CMP_EQ_U32 killed %2, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.4, implicit killed $scc
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    S_CMP_EQ_U32 killed %3, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.5, implicit killed $scc
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Uniform, 1: Divergent, 2: Uniform
---
name: partial_join_6
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_6
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1, $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.5(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY2]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.5, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_MOV_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $vgpr0, $sgpr1

    %1:sgpr_32 = COPY $sgpr0
    %2:vgpr_32 = COPY $vgpr0
    %3:sgpr_32 = COPY $sgpr1
    %4:sreg_32 = S_MOV_B32 0
    S_CMP_EQ_U32 killed %1, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit killed $scc
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %6:sreg_32 = V_CMP_EQ_U32_e64 killed %2, %4, implicit $exec
    SI_BRCOND %bb.4, killed %6, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    S_CMP_EQ_U32 killed %3, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.5, implicit killed $scc
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0

...
#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#  3    4    5
#   \   |   /
#     ->6<-
#
# 0: Uniform, 1: Uniform, 2: Divergent
---
name: partial_join_7
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: partial_join_7
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1, $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_CMP_EQ_U32 killed [[COPY1]], [[S_MOV_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_SCC1 %bb.4, implicit $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_XOR_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_MOV_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_MOV_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = COPY [[S_AND_B32_]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32 [[S_MOV_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_MOV_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $sgpr1, $vgpr0

    %1:sgpr_32 = COPY $sgpr0
    %2:sgpr_32 = COPY $sgpr1
    %3:vgpr_32 = COPY $vgpr0
    %4:sreg_32 = S_MOV_B32 0
    S_CMP_EQ_U32 killed %1, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit killed $scc
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    S_CMP_EQ_U32 killed %2, %4, implicit-def $scc
    S_CBRANCH_SCC1 %bb.4, implicit killed $scc
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.4, %bb.5

    %7:sreg_32 = V_CMP_EQ_U32_e64 killed %3, %4, implicit $exec
    SI_BRCOND %bb.5, killed %7, implicit-def dead $exec, implicit-def dead $vcc, implicit $exec
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.4:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6
    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0
...
