# This CI workflow is triggered by:
#   - scheduled run
#
# In the scheduled run, we run all targets from amdgpu_family_matrix.py and amdgpu_family_matrix_xfail.py
# As some of these builds are xfail, we allow errors to occur with `continue-on-error`, where the job will fail but the workflow is green

name: CI amd-staging Nightly

on:
  # For AMD GPU families that expect_failure, we run builds and tests from this scheduled trigger
  schedule:
    - cron: "0 2 * * *" # Runs nightly at 2 AM UTC
  workflow_dispatch:
    inputs:
      linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      linux_test_labels:
        type: string
        description: "If enabled, reduce test set on Linux to the list of labels prefixed with 'test:'"
        default: ""
      linux_use_prebuilt_artifacts:
        type: boolean
        description: "If enabled, the CI will pull Linux artifacts using artifact_run_id and only run tests"
      windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      windows_test_labels:
        type: string
        description: "If enabled, reduce test set on Windows to the list of labels prefixed with 'test:'"
        default: ""
      windows_use_prebuilt_artifacts:
        type: boolean
        description: "If enabled, the CI will pull Windows artifacts using artifact_run_id and only run tests"
      artifact_run_id:
        type: string
        description: "If provided, the tests will run on this artifact ID"
        default: ""

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  notify_build_status:
    name: Notify amd-staging nightly status
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: Download and Extract URLs from logs
        id: extract_urls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          THE_ROCK_MANIFEST_URL="https://therock-ci-artifacts-external.s3.amazonaws.com/ROCm-llvm-project/22166651119-linux/manifests/gfx94X-dcgpu/therock_manifest.json"
          ARTIFACTS_URL="https://therock-ci-artifacts-external.s3.amazonaws.com/ROCm-llvm-project/22166651119-linux/index-gfx94X-dcgpu.html"
          BUILD_LOGS_URL="https://therock-ci-artifacts-external.s3.amazonaws.com/ROCm-llvm-project/22166651119-linux/logs/gfx94X-dcgpu/index.html"
          # Fetch the manifest JSON from THE_ROCK_MANIFEST_URL
          curl -L "$THE_ROCK_MANIFEST_URL" -o manifest.json
          # Set the URLs as outputs
          echo "THE_ROCK_MANIFEST_URL=$THE_ROCK_MANIFEST_URL" >> $GITHUB_ENV
          echo "ARTIFACTS_URL=$ARTIFACTS_URL" >> $GITHUB_ENV
          echo "BUILD_LOGS_URL=$BUILD_LOGS_URL" >> $GITHUB_ENV

      - name: Notify status
        env:
          TZ: 'America/Chicago'
        run: |
          START_DATE=$(date +"%Y-%m-%d")  # Use the current date for the report
          
          # Initialize the status to failure
          STATUS="success"

          # Check the results of the dependent jobs
          #if [[ "${{ needs.windows_build_and_test.result }}" =~ ^(failure|cancelled)$ ]] || [[ "${{ needs.linux_build_and_test.result }}" =~ ^(failure|cancelled)$ ]]; then
          #  STATUS="failure"
          #elif [[ "${{ needs.windows_build_and_test.result }}" = "success" ]] && [[ "${{ needs.linux_build_and_test.result }}" = "success" ]]; then
          #  STATUS="success"
          #fi
          
          # Determine the icon based on the status
          ICON="ℹ️"
          if [ "$STATUS" = "success" ]; then ICON="✅"; fi
          if [ "$STATUS" = "failure" ]; then ICON="❌"; fi      

          WEBHOOK_URL="${{ secrets.NOTIFIER_TESTTING_WEBHOOK_URL }}"      
          
          # Extract submodule information and create a table
          SUBMODULE_TABLE=$(python -c "
          import json
          with open('manifest.json') as f:
            data = json.load(f)
          the_rock_commit = data.get('the_rock_commit', '')
          commit_url = f'https://github.com/ROCm/therock/commit/{the_rock_commit}'
          table = '| TheRock Commit | URL |\n|----------------|-----|\n'
          table += f'| {the_rock_commit} | ({commit_url}) |\n\n'
          table += '| Submodule | Commit |\n|-----------|--------|\n'
          for submodule in data['submodules']:
            submodule_name = submodule['submodule_name']
            submodule_url = submodule['submodule_url']
            pin_sha = submodule['pin_sha']
            commit_url = f'{submodule_url.replace('.git', '')}/commit/{pin_sha}'
            table += f'| {submodule_name} | ({commit_url}) |\n'
          print(table)
          ")

          # Prepare notification content
          NOTIFICATION_CONTENT="{
            \"title\": \"$START_DATE - $ICON Build $STATUS\",
            \"text\": \"**Repository:** ${{ github.repository }}  \n\
            **Branch:** ${{ github.ref_name }}  \n\
            **Status:** $STATUS  \n\
            🔗 [Build Link](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n\
            **Links:**\n\n\
            | Description | URL |\n\
            |-------------|-----|\n\
            | TheRock Manifest | [TheRock Manifest]($THE_ROCK_MANIFEST_URL) |\n\
            | Artifacts | [Artifacts]($ARTIFACTS_URL) |\n\
            | Build Logs | [Build Logs]($BUILD_LOGS_URL) |\n\n\
            \n\n\
            $SUBMODULE_TABLE\"
          }"

          # Echo the notification content for debugging
          echo "$NOTIFICATION_CONTENT"

          # Commented out the actual sending of the notification
          curl -H "Content-Type: application/json" -d "$NOTIFICATION_CONTENT" "$WEBHOOK_URL"


  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
